Version: 1

Host: 0.0.0.0
Port: 8081

Cache:
  Engine: redis
  Host: localhost
  Port: 6379
  Pass:
  DB: 0
  LifeTime: 60

Database:
  Driver: mysql
  Host: localhost
  Port: 3306
  User: user1
  Pass: 111111
  DbName: sds
  Debug: false
  LogFile: tmp/logs/db_api.log

LogFile: tmp/logs/stdout_api.log

Debug: true
