Version: 1

Net:
  Host: 0.0.0.0
  Port: 8888
  WebsocketPort: 8889

HashRing:
  VirtualNodeNum: 20

FileStorage:
  SliceBlockSize: 33554432

Cache:
  Engine: redis
  Host: localhost
  Port: 6379
  Pass:
  DB: 0
  LifeTime: 60

Database:
  Driver: mysql
  Host: localhost
  Port: 3306
  User: user1
  Pass: 111111
  DbName: sds
  Debug: false
  LogFile: tmp/logs/db.log

BpList:
  - { NetworkAddress: 192.168.2.43:18081, WalletAddress: st1cdsw4wmrd6w9a7gsez2mxadfrkxltj7685aj83 }
  - { NetworkAddress: 192.168.2.43:18082, WalletAddress: st1jzkud0tt88y6tyg6675utue45z5a04er4hfp9n }

Ecdsa:
  PrivateKeyPath: path_to_privatekey
  PrivateKeyPass: privatekey_password

BlockchainInfo:
  AddressPrefix: st
  ChainId: stratoschain
  Token: stos