Version: 1

Net:
  Host: 0.0.0.0
  Port: 8888
  WebsocketPort: 8889

HashRing:
  VirtualNodeNum: 20

FileStorage:
  SliceBlockSize: 33554432

Cache:
  Engine: redis
  Host: localhost
  Port: 6379
  Pass:
  DB: 0
  LifeTime: 60

Database:
  Driver: mysql
  Host: localhost
  Port: 3306
  User: user1
  Pass: 111111
  DbName: sds
  Debug: true
  LogFile: tmp/logs/db.log

Ecdsa:
  PrivateKeyPath: configs/node_key.json
  PrivateKeyPass: aaa

BlockchainInfo:
  AddressPrefix: st
  ChainId: test-chain
  StratosChainAddress: 127.0.0.1
  StratosChainPort: 1317
  Token: ustos
  Transactions:
    Fee: 1
    Gas: 100000

Log:
  Path: tmp/logs/sp-server.log
  Level: 1
  OutputFile: true
  OutputStd: true
