// Code generated by protoc-gen-go. DO NOT EDIT.
// source: relay.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResultState int32

const (
	ResultState_RES_SUCCESS ResultState = 0
	ResultState_RES_FAIL    ResultState = 1
)

var ResultState_name = map[int32]string{
	0: "RES_SUCCESS",
	1: "RES_FAIL",
}

var ResultState_value = map[string]int32{
	"RES_SUCCESS": 0,
	"RES_FAIL":    1,
}

func (x ResultState) String() string {
	return proto.EnumName(ResultState_name, int32(x))
}

func (ResultState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9f69a7d5a802d584, []int{0}
}

type Result struct {
	State                ResultState `protobuf:"varint,1,opt,name=state,proto3,enum=protos.ResultState" json:"state,omitempty"`
	Msg                  string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f69a7d5a802d584, []int{0}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetState() ResultState {
	if m != nil {
		return m.State
	}
	return ResultState_RES_SUCCESS
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Uploaded struct {
	ReporterAddress      string   `protobuf:"bytes,1,opt,name=reporter_address,json=reporterAddress,proto3" json:"reporter_address,omitempty"`
	UploaderAddress      string   `protobuf:"bytes,2,opt,name=uploader_address,json=uploaderAddress,proto3" json:"uploader_address,omitempty"`
	FileHash             string   `protobuf:"bytes,3,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	TxHash               string   `protobuf:"bytes,4,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Uploaded) Reset()         { *m = Uploaded{} }
func (m *Uploaded) String() string { return proto.CompactTextString(m) }
func (*Uploaded) ProtoMessage()    {}
func (*Uploaded) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f69a7d5a802d584, []int{1}
}

func (m *Uploaded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Uploaded.Unmarshal(m, b)
}
func (m *Uploaded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Uploaded.Marshal(b, m, deterministic)
}
func (m *Uploaded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uploaded.Merge(m, src)
}
func (m *Uploaded) XXX_Size() int {
	return xxx_messageInfo_Uploaded.Size(m)
}
func (m *Uploaded) XXX_DiscardUnknown() {
	xxx_messageInfo_Uploaded.DiscardUnknown(m)
}

var xxx_messageInfo_Uploaded proto.InternalMessageInfo

func (m *Uploaded) GetReporterAddress() string {
	if m != nil {
		return m.ReporterAddress
	}
	return ""
}

func (m *Uploaded) GetUploaderAddress() string {
	if m != nil {
		return m.UploaderAddress
	}
	return ""
}

func (m *Uploaded) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *Uploaded) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

type ReqActivatedPP struct {
	P2PAddress           string   `protobuf:"bytes,1,opt,name=p2p_address,json=p2pAddress,proto3" json:"p2p_address,omitempty"`
	P2PPubkey            string   `protobuf:"bytes,2,opt,name=p2p_pubkey,json=p2pPubkey,proto3" json:"p2p_pubkey,omitempty"`
	OzoneLimitChanges    string   `protobuf:"bytes,3,opt,name=ozone_limit_changes,json=ozoneLimitChanges,proto3" json:"ozone_limit_changes,omitempty"`
	TxHash               string   `protobuf:"bytes,4,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	InitialDeposit       string   `protobuf:"bytes,5,opt,name=initial_deposit,json=initialDeposit,proto3" json:"initial_deposit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqActivatedPP) Reset()         { *m = ReqActivatedPP{} }
func (m *ReqActivatedPP) String() string { return proto.CompactTextString(m) }
func (*ReqActivatedPP) ProtoMessage()    {}
func (*ReqActivatedPP) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f69a7d5a802d584, []int{2}
}

func (m *ReqActivatedPP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqActivatedPP.Unmarshal(m, b)
}
func (m *ReqActivatedPP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqActivatedPP.Marshal(b, m, deterministic)
}
func (m *ReqActivatedPP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqActivatedPP.Merge(m, src)
}
func (m *ReqActivatedPP) XXX_Size() int {
	return xxx_messageInfo_ReqActivatedPP.Size(m)
}
func (m *ReqActivatedPP) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqActivatedPP.DiscardUnknown(m)
}

var xxx_messageInfo_ReqActivatedPP proto.InternalMessageInfo

func (m *ReqActivatedPP) GetP2PAddress() string {
	if m != nil {
		return m.P2PAddress
	}
	return ""
}

func (m *ReqActivatedPP) GetP2PPubkey() string {
	if m != nil {
		return m.P2PPubkey
	}
	return ""
}

func (m *ReqActivatedPP) GetOzoneLimitChanges() string {
	if m != nil {
		return m.OzoneLimitChanges
	}
	return ""
}

func (m *ReqActivatedPP) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *ReqActivatedPP) GetInitialDeposit() string {
	if m != nil {
		return m.InitialDeposit
	}
	return ""
}

type ReqActivatedSP struct {
	P2PAddress           string   `protobuf:"bytes,1,opt,name=p2p_address,json=p2pAddress,proto3" json:"p2p_address,omitempty"`
	OzoneLimitChanges    string   `protobuf:"bytes,2,opt,name=ozone_limit_changes,json=ozoneLimitChanges,proto3" json:"ozone_limit_changes,omitempty"`
	TxHash               string   `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqActivatedSP) Reset()         { *m = ReqActivatedSP{} }
func (m *ReqActivatedSP) String() string { return proto.CompactTextString(m) }
func (*ReqActivatedSP) ProtoMessage()    {}
func (*ReqActivatedSP) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f69a7d5a802d584, []int{3}
}

func (m *ReqActivatedSP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqActivatedSP.Unmarshal(m, b)
}
func (m *ReqActivatedSP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqActivatedSP.Marshal(b, m, deterministic)
}
func (m *ReqActivatedSP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqActivatedSP.Merge(m, src)
}
func (m *ReqActivatedSP) XXX_Size() int {
	return xxx_messageInfo_ReqActivatedSP.Size(m)
}
func (m *ReqActivatedSP) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqActivatedSP.DiscardUnknown(m)
}

var xxx_messageInfo_ReqActivatedSP proto.InternalMessageInfo

func (m *ReqActivatedSP) GetP2PAddress() string {
	if m != nil {
		return m.P2PAddress
	}
	return ""
}

func (m *ReqActivatedSP) GetOzoneLimitChanges() string {
	if m != nil {
		return m.OzoneLimitChanges
	}
	return ""
}

func (m *ReqActivatedSP) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

type RspActivatedPP struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspActivatedPP) Reset()         { *m = RspActivatedPP{} }
func (m *RspActivatedPP) String() string { return proto.CompactTextString(m) }
func (*RspActivatedPP) ProtoMessage()    {}
func (*RspActivatedPP) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f69a7d5a802d584, []int{4}
}

func (m *RspActivatedPP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspActivatedPP.Unmarshal(m, b)
}
func (m *RspActivatedPP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspActivatedPP.Marshal(b, m, deterministic)
}
func (m *RspActivatedPP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspActivatedPP.Merge(m, src)
}
func (m *RspActivatedPP) XXX_Size() int {
	return xxx_messageInfo_RspActivatedPP.Size(m)
}
func (m *RspActivatedPP) XXX_DiscardUnknown() {
	xxx_messageInfo_RspActivatedPP.DiscardUnknown(m)
}

var xxx_messageInfo_RspActivatedPP proto.InternalMessageInfo

func (m *RspActivatedPP) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReqUpdatedDepositPP struct {
	P2PAddress           string   `protobuf:"bytes,1,opt,name=p2p_address,json=p2pAddress,proto3" json:"p2p_address,omitempty"`
	OzoneLimitChanges    string   `protobuf:"bytes,2,opt,name=ozone_limit_changes,json=ozoneLimitChanges,proto3" json:"ozone_limit_changes,omitempty"`
	TxHash               string   `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	DepositDelta         string   `protobuf:"bytes,4,opt,name=deposit_delta,json=depositDelta,proto3" json:"deposit_delta,omitempty"`
	CurrentDeposit       string   `protobuf:"bytes,5,opt,name=current_deposit,json=currentDeposit,proto3" json:"current_deposit,omitempty"`
	AvailableTokenBefore string   `protobuf:"bytes,6,opt,name=available_token_before,json=availableTokenBefore,proto3" json:"available_token_before,omitempty"`
	AvailableTokenAfter  string   `protobuf:"bytes,7,opt,name=available_token_after,json=availableTokenAfter,proto3" json:"available_token_after,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUpdatedDepositPP) Reset()         { *m = ReqUpdatedDepositPP{} }
func (m *ReqUpdatedDepositPP) String() string { return proto.CompactTextString(m) }
func (*ReqUpdatedDepositPP) ProtoMessage()    {}
func (*ReqUpdatedDepositPP) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f69a7d5a802d584, []int{5}
}

func (m *ReqUpdatedDepositPP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUpdatedDepositPP.Unmarshal(m, b)
}
func (m *ReqUpdatedDepositPP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUpdatedDepositPP.Marshal(b, m, deterministic)
}
func (m *ReqUpdatedDepositPP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUpdatedDepositPP.Merge(m, src)
}
func (m *ReqUpdatedDepositPP) XXX_Size() int {
	return xxx_messageInfo_ReqUpdatedDepositPP.Size(m)
}
func (m *ReqUpdatedDepositPP) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUpdatedDepositPP.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUpdatedDepositPP proto.InternalMessageInfo

func (m *ReqUpdatedDepositPP) GetP2PAddress() string {
	if m != nil {
		return m.P2PAddress
	}
	return ""
}

func (m *ReqUpdatedDepositPP) GetOzoneLimitChanges() string {
	if m != nil {
		return m.OzoneLimitChanges
	}
	return ""
}

func (m *ReqUpdatedDepositPP) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *ReqUpdatedDepositPP) GetDepositDelta() string {
	if m != nil {
		return m.DepositDelta
	}
	return ""
}

func (m *ReqUpdatedDepositPP) GetCurrentDeposit() string {
	if m != nil {
		return m.CurrentDeposit
	}
	return ""
}

func (m *ReqUpdatedDepositPP) GetAvailableTokenBefore() string {
	if m != nil {
		return m.AvailableTokenBefore
	}
	return ""
}

func (m *ReqUpdatedDepositPP) GetAvailableTokenAfter() string {
	if m != nil {
		return m.AvailableTokenAfter
	}
	return ""
}

type ReqUpdatedDepositSP struct {
	P2PAddress           string   `protobuf:"bytes,1,opt,name=p2p_address,json=p2pAddress,proto3" json:"p2p_address,omitempty"`
	OzoneLimitChanges    string   `protobuf:"bytes,2,opt,name=ozone_limit_changes,json=ozoneLimitChanges,proto3" json:"ozone_limit_changes,omitempty"`
	TxHash               string   `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	DepositDelta         string   `protobuf:"bytes,4,opt,name=deposit_delta,json=depositDelta,proto3" json:"deposit_delta,omitempty"`
	CurrentDeposit       string   `protobuf:"bytes,5,opt,name=current_deposit,json=currentDeposit,proto3" json:"current_deposit,omitempty"`
	AvailableTokenBefore string   `protobuf:"bytes,6,opt,name=available_token_before,json=availableTokenBefore,proto3" json:"available_token_before,omitempty"`
	AvailableTokenAfter  string   `protobuf:"bytes,7,opt,name=available_token_after,json=availableTokenAfter,proto3" json:"available_token_after,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUpdatedDepositSP) Reset()         { *m = ReqUpdatedDepositSP{} }
func (m *ReqUpdatedDepositSP) String() string { return proto.CompactTextString(m) }
func (*ReqUpdatedDepositSP) ProtoMessage()    {}
func (*ReqUpdatedDepositSP) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f69a7d5a802d584, []int{6}
}

func (m *ReqUpdatedDepositSP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUpdatedDepositSP.Unmarshal(m, b)
}
func (m *ReqUpdatedDepositSP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUpdatedDepositSP.Marshal(b, m, deterministic)
}
func (m *ReqUpdatedDepositSP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUpdatedDepositSP.Merge(m, src)
}
func (m *ReqUpdatedDepositSP) XXX_Size() int {
	return xxx_messageInfo_ReqUpdatedDepositSP.Size(m)
}
func (m *ReqUpdatedDepositSP) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUpdatedDepositSP.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUpdatedDepositSP proto.InternalMessageInfo

func (m *ReqUpdatedDepositSP) GetP2PAddress() string {
	if m != nil {
		return m.P2PAddress
	}
	return ""
}

func (m *ReqUpdatedDepositSP) GetOzoneLimitChanges() string {
	if m != nil {
		return m.OzoneLimitChanges
	}
	return ""
}

func (m *ReqUpdatedDepositSP) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *ReqUpdatedDepositSP) GetDepositDelta() string {
	if m != nil {
		return m.DepositDelta
	}
	return ""
}

func (m *ReqUpdatedDepositSP) GetCurrentDeposit() string {
	if m != nil {
		return m.CurrentDeposit
	}
	return ""
}

func (m *ReqUpdatedDepositSP) GetAvailableTokenBefore() string {
	if m != nil {
		return m.AvailableTokenBefore
	}
	return ""
}

func (m *ReqUpdatedDepositSP) GetAvailableTokenAfter() string {
	if m != nil {
		return m.AvailableTokenAfter
	}
	return ""
}

type ReqDeactivatedPP struct {
	P2PAddress           string   `protobuf:"bytes,1,opt,name=p2p_address,json=p2pAddress,proto3" json:"p2p_address,omitempty"`
	TxHash               string   `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDeactivatedPP) Reset()         { *m = ReqDeactivatedPP{} }
func (m *ReqDeactivatedPP) String() string { return proto.CompactTextString(m) }
func (*ReqDeactivatedPP) ProtoMessage()    {}
func (*ReqDeactivatedPP) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f69a7d5a802d584, []int{7}
}

func (m *ReqDeactivatedPP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDeactivatedPP.Unmarshal(m, b)
}
func (m *ReqDeactivatedPP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDeactivatedPP.Marshal(b, m, deterministic)
}
func (m *ReqDeactivatedPP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDeactivatedPP.Merge(m, src)
}
func (m *ReqDeactivatedPP) XXX_Size() int {
	return xxx_messageInfo_ReqDeactivatedPP.Size(m)
}
func (m *ReqDeactivatedPP) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDeactivatedPP.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDeactivatedPP proto.InternalMessageInfo

func (m *ReqDeactivatedPP) GetP2PAddress() string {
	if m != nil {
		return m.P2PAddress
	}
	return ""
}

func (m *ReqDeactivatedPP) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

type ReqUnbondingPP struct {
	P2PAddress           string   `protobuf:"bytes,1,opt,name=p2p_address,json=p2pAddress,proto3" json:"p2p_address,omitempty"`
	OzoneLimitChanges    string   `protobuf:"bytes,2,opt,name=ozone_limit_changes,json=ozoneLimitChanges,proto3" json:"ozone_limit_changes,omitempty"`
	UnbondingMatureTime  string   `protobuf:"bytes,3,opt,name=unbonding_mature_time,json=unbondingMatureTime,proto3" json:"unbonding_mature_time,omitempty"`
	TxHash               string   `protobuf:"bytes,4,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	DepositToRemove      string   `protobuf:"bytes,5,opt,name=deposit_to_remove,json=depositToRemove,proto3" json:"deposit_to_remove,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUnbondingPP) Reset()         { *m = ReqUnbondingPP{} }
func (m *ReqUnbondingPP) String() string { return proto.CompactTextString(m) }
func (*ReqUnbondingPP) ProtoMessage()    {}
func (*ReqUnbondingPP) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f69a7d5a802d584, []int{8}
}

func (m *ReqUnbondingPP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUnbondingPP.Unmarshal(m, b)
}
func (m *ReqUnbondingPP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUnbondingPP.Marshal(b, m, deterministic)
}
func (m *ReqUnbondingPP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUnbondingPP.Merge(m, src)
}
func (m *ReqUnbondingPP) XXX_Size() int {
	return xxx_messageInfo_ReqUnbondingPP.Size(m)
}
func (m *ReqUnbondingPP) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUnbondingPP.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUnbondingPP proto.InternalMessageInfo

func (m *ReqUnbondingPP) GetP2PAddress() string {
	if m != nil {
		return m.P2PAddress
	}
	return ""
}

func (m *ReqUnbondingPP) GetOzoneLimitChanges() string {
	if m != nil {
		return m.OzoneLimitChanges
	}
	return ""
}

func (m *ReqUnbondingPP) GetUnbondingMatureTime() string {
	if m != nil {
		return m.UnbondingMatureTime
	}
	return ""
}

func (m *ReqUnbondingPP) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *ReqUnbondingPP) GetDepositToRemove() string {
	if m != nil {
		return m.DepositToRemove
	}
	return ""
}

type ReqUnbondingSP struct {
	P2PAddress           string   `protobuf:"bytes,1,opt,name=p2p_address,json=p2pAddress,proto3" json:"p2p_address,omitempty"`
	OzoneLimitChanges    string   `protobuf:"bytes,2,opt,name=ozone_limit_changes,json=ozoneLimitChanges,proto3" json:"ozone_limit_changes,omitempty"`
	UnbondingMatureTime  string   `protobuf:"bytes,3,opt,name=unbonding_mature_time,json=unbondingMatureTime,proto3" json:"unbonding_mature_time,omitempty"`
	TxHash               string   `protobuf:"bytes,4,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	DepositToRemove      string   `protobuf:"bytes,5,opt,name=deposit_to_remove,json=depositToRemove,proto3" json:"deposit_to_remove,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUnbondingSP) Reset()         { *m = ReqUnbondingSP{} }
func (m *ReqUnbondingSP) String() string { return proto.CompactTextString(m) }
func (*ReqUnbondingSP) ProtoMessage()    {}
func (*ReqUnbondingSP) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f69a7d5a802d584, []int{9}
}

func (m *ReqUnbondingSP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUnbondingSP.Unmarshal(m, b)
}
func (m *ReqUnbondingSP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUnbondingSP.Marshal(b, m, deterministic)
}
func (m *ReqUnbondingSP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUnbondingSP.Merge(m, src)
}
func (m *ReqUnbondingSP) XXX_Size() int {
	return xxx_messageInfo_ReqUnbondingSP.Size(m)
}
func (m *ReqUnbondingSP) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUnbondingSP.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUnbondingSP proto.InternalMessageInfo

func (m *ReqUnbondingSP) GetP2PAddress() string {
	if m != nil {
		return m.P2PAddress
	}
	return ""
}

func (m *ReqUnbondingSP) GetOzoneLimitChanges() string {
	if m != nil {
		return m.OzoneLimitChanges
	}
	return ""
}

func (m *ReqUnbondingSP) GetUnbondingMatureTime() string {
	if m != nil {
		return m.UnbondingMatureTime
	}
	return ""
}

func (m *ReqUnbondingSP) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *ReqUnbondingSP) GetDepositToRemove() string {
	if m != nil {
		return m.DepositToRemove
	}
	return ""
}

type ReqWithdrawnDepositSP struct {
	P2PAddress           string   `protobuf:"bytes,1,opt,name=p2p_address,json=p2pAddress,proto3" json:"p2p_address,omitempty"`
	UnbondingMatureTime  string   `protobuf:"bytes,2,opt,name=unbonding_mature_time,json=unbondingMatureTime,proto3" json:"unbonding_mature_time,omitempty"`
	TxHash               string   `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqWithdrawnDepositSP) Reset()         { *m = ReqWithdrawnDepositSP{} }
func (m *ReqWithdrawnDepositSP) String() string { return proto.CompactTextString(m) }
func (*ReqWithdrawnDepositSP) ProtoMessage()    {}
func (*ReqWithdrawnDepositSP) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f69a7d5a802d584, []int{10}
}

func (m *ReqWithdrawnDepositSP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqWithdrawnDepositSP.Unmarshal(m, b)
}
func (m *ReqWithdrawnDepositSP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqWithdrawnDepositSP.Marshal(b, m, deterministic)
}
func (m *ReqWithdrawnDepositSP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqWithdrawnDepositSP.Merge(m, src)
}
func (m *ReqWithdrawnDepositSP) XXX_Size() int {
	return xxx_messageInfo_ReqWithdrawnDepositSP.Size(m)
}
func (m *ReqWithdrawnDepositSP) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqWithdrawnDepositSP.DiscardUnknown(m)
}

var xxx_messageInfo_ReqWithdrawnDepositSP proto.InternalMessageInfo

func (m *ReqWithdrawnDepositSP) GetP2PAddress() string {
	if m != nil {
		return m.P2PAddress
	}
	return ""
}

func (m *ReqWithdrawnDepositSP) GetUnbondingMatureTime() string {
	if m != nil {
		return m.UnbondingMatureTime
	}
	return ""
}

func (m *ReqWithdrawnDepositSP) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

type RspWithdrawnDepositSP struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspWithdrawnDepositSP) Reset()         { *m = RspWithdrawnDepositSP{} }
func (m *RspWithdrawnDepositSP) String() string { return proto.CompactTextString(m) }
func (*RspWithdrawnDepositSP) ProtoMessage()    {}
func (*RspWithdrawnDepositSP) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f69a7d5a802d584, []int{11}
}

func (m *RspWithdrawnDepositSP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspWithdrawnDepositSP.Unmarshal(m, b)
}
func (m *RspWithdrawnDepositSP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspWithdrawnDepositSP.Marshal(b, m, deterministic)
}
func (m *RspWithdrawnDepositSP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspWithdrawnDepositSP.Merge(m, src)
}
func (m *RspWithdrawnDepositSP) XXX_Size() int {
	return xxx_messageInfo_RspWithdrawnDepositSP.Size(m)
}
func (m *RspWithdrawnDepositSP) XXX_DiscardUnknown() {
	xxx_messageInfo_RspWithdrawnDepositSP.DiscardUnknown(m)
}

var xxx_messageInfo_RspWithdrawnDepositSP proto.InternalMessageInfo

func (m *RspWithdrawnDepositSP) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReqDeactivatedSP struct {
	P2PAddress           string   `protobuf:"bytes,1,opt,name=p2p_address,json=p2pAddress,proto3" json:"p2p_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDeactivatedSP) Reset()         { *m = ReqDeactivatedSP{} }
func (m *ReqDeactivatedSP) String() string { return proto.CompactTextString(m) }
func (*ReqDeactivatedSP) ProtoMessage()    {}
func (*ReqDeactivatedSP) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f69a7d5a802d584, []int{12}
}

func (m *ReqDeactivatedSP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDeactivatedSP.Unmarshal(m, b)
}
func (m *ReqDeactivatedSP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDeactivatedSP.Marshal(b, m, deterministic)
}
func (m *ReqDeactivatedSP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDeactivatedSP.Merge(m, src)
}
func (m *ReqDeactivatedSP) XXX_Size() int {
	return xxx_messageInfo_ReqDeactivatedSP.Size(m)
}
func (m *ReqDeactivatedSP) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDeactivatedSP.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDeactivatedSP proto.InternalMessageInfo

func (m *ReqDeactivatedSP) GetP2PAddress() string {
	if m != nil {
		return m.P2PAddress
	}
	return ""
}

type RspDeactivatedSP struct {
	Result               *Result  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspDeactivatedSP) Reset()         { *m = RspDeactivatedSP{} }
func (m *RspDeactivatedSP) String() string { return proto.CompactTextString(m) }
func (*RspDeactivatedSP) ProtoMessage()    {}
func (*RspDeactivatedSP) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f69a7d5a802d584, []int{13}
}

func (m *RspDeactivatedSP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspDeactivatedSP.Unmarshal(m, b)
}
func (m *RspDeactivatedSP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspDeactivatedSP.Marshal(b, m, deterministic)
}
func (m *RspDeactivatedSP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspDeactivatedSP.Merge(m, src)
}
func (m *RspDeactivatedSP) XXX_Size() int {
	return xxx_messageInfo_RspDeactivatedSP.Size(m)
}
func (m *RspDeactivatedSP) XXX_DiscardUnknown() {
	xxx_messageInfo_RspDeactivatedSP.DiscardUnknown(m)
}

var xxx_messageInfo_RspDeactivatedSP proto.InternalMessageInfo

func (m *RspDeactivatedSP) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReqPrepaid struct {
	WalletAddress        string   `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	PurchasedUoz         string   `protobuf:"bytes,2,opt,name=purchased_uoz,json=purchasedUoz,proto3" json:"purchased_uoz,omitempty"`
	TxHash               string   `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPrepaid) Reset()         { *m = ReqPrepaid{} }
func (m *ReqPrepaid) String() string { return proto.CompactTextString(m) }
func (*ReqPrepaid) ProtoMessage()    {}
func (*ReqPrepaid) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f69a7d5a802d584, []int{14}
}

func (m *ReqPrepaid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPrepaid.Unmarshal(m, b)
}
func (m *ReqPrepaid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPrepaid.Marshal(b, m, deterministic)
}
func (m *ReqPrepaid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPrepaid.Merge(m, src)
}
func (m *ReqPrepaid) XXX_Size() int {
	return xxx_messageInfo_ReqPrepaid.Size(m)
}
func (m *ReqPrepaid) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPrepaid.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPrepaid proto.InternalMessageInfo

func (m *ReqPrepaid) GetWalletAddress() string {
	if m != nil {
		return m.WalletAddress
	}
	return ""
}

func (m *ReqPrepaid) GetPurchasedUoz() string {
	if m != nil {
		return m.PurchasedUoz
	}
	return ""
}

func (m *ReqPrepaid) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

type RelayMessage struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelayMessage) Reset()         { *m = RelayMessage{} }
func (m *RelayMessage) String() string { return proto.CompactTextString(m) }
func (*RelayMessage) ProtoMessage()    {}
func (*RelayMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f69a7d5a802d584, []int{15}
}

func (m *RelayMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelayMessage.Unmarshal(m, b)
}
func (m *RelayMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelayMessage.Marshal(b, m, deterministic)
}
func (m *RelayMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayMessage.Merge(m, src)
}
func (m *RelayMessage) XXX_Size() int {
	return xxx_messageInfo_RelayMessage.Size(m)
}
func (m *RelayMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RelayMessage proto.InternalMessageInfo

func (m *RelayMessage) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RelayMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("protos.ResultState", ResultState_name, ResultState_value)
	proto.RegisterType((*Result)(nil), "protos.Result")
	proto.RegisterType((*Uploaded)(nil), "protos.Uploaded")
	proto.RegisterType((*ReqActivatedPP)(nil), "protos.ReqActivatedPP")
	proto.RegisterType((*ReqActivatedSP)(nil), "protos.ReqActivatedSP")
	proto.RegisterType((*RspActivatedPP)(nil), "protos.RspActivatedPP")
	proto.RegisterType((*ReqUpdatedDepositPP)(nil), "protos.ReqUpdatedDepositPP")
	proto.RegisterType((*ReqUpdatedDepositSP)(nil), "protos.ReqUpdatedDepositSP")
	proto.RegisterType((*ReqDeactivatedPP)(nil), "protos.ReqDeactivatedPP")
	proto.RegisterType((*ReqUnbondingPP)(nil), "protos.ReqUnbondingPP")
	proto.RegisterType((*ReqUnbondingSP)(nil), "protos.ReqUnbondingSP")
	proto.RegisterType((*ReqWithdrawnDepositSP)(nil), "protos.ReqWithdrawnDepositSP")
	proto.RegisterType((*RspWithdrawnDepositSP)(nil), "protos.RspWithdrawnDepositSP")
	proto.RegisterType((*ReqDeactivatedSP)(nil), "protos.ReqDeactivatedSP")
	proto.RegisterType((*RspDeactivatedSP)(nil), "protos.RspDeactivatedSP")
	proto.RegisterType((*ReqPrepaid)(nil), "protos.ReqPrepaid")
	proto.RegisterType((*RelayMessage)(nil), "protos.RelayMessage")
}

func init() { proto.RegisterFile("relay.proto", fileDescriptor_9f69a7d5a802d584) }

var fileDescriptor_9f69a7d5a802d584 = []byte{
	// 732 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0xdd, 0x6e, 0x1a, 0x39,
	0x14, 0x5e, 0x48, 0x42, 0xc2, 0x81, 0x00, 0x31, 0xcb, 0x2e, 0xd2, 0x6a, 0xb5, 0x11, 0x51, 0x36,
	0x3f, 0xaa, 0x40, 0x22, 0x55, 0x55, 0xf5, 0xa6, 0x22, 0x3f, 0x55, 0x2b, 0x25, 0x12, 0xf2, 0x04,
	0x55, 0xea, 0xcd, 0xc8, 0x30, 0x27, 0x30, 0xca, 0x30, 0x36, 0xb6, 0x27, 0x3f, 0xdc, 0xf7, 0x15,
	0xfa, 0x2a, 0xbd, 0xef, 0x63, 0xf4, 0x69, 0x2a, 0x7b, 0x86, 0x34, 0xd0, 0xa0, 0x92, 0x8b, 0xf6,
	0xa2, 0xea, 0x15, 0xe6, 0xfb, 0xce, 0xf1, 0xf9, 0xce, 0xe7, 0x33, 0x96, 0x21, 0x27, 0x31, 0x60,
	0xb7, 0x75, 0x21, 0xb9, 0xe6, 0x24, 0x63, 0x7f, 0x54, 0xed, 0x04, 0x32, 0x14, 0x55, 0x14, 0x68,
	0xb2, 0x07, 0x2b, 0x4a, 0x33, 0x8d, 0xd5, 0xd4, 0x66, 0x6a, 0xb7, 0xd0, 0x2c, 0xc7, 0x81, 0xaa,
	0x1e, 0xd3, 0x8e, 0xa1, 0x68, 0x1c, 0x41, 0x4a, 0xb0, 0x34, 0x54, 0xfd, 0x6a, 0x7a, 0x33, 0xb5,
	0x9b, 0xa5, 0x66, 0x59, 0xfb, 0x90, 0x82, 0xb5, 0x8e, 0x08, 0x38, 0xf3, 0xd0, 0x23, 0x7b, 0x50,
	0x92, 0x28, 0xb8, 0xd4, 0x28, 0x5d, 0xe6, 0x79, 0x12, 0x95, 0xb2, 0x9b, 0x66, 0x69, 0x71, 0x82,
	0xb7, 0x62, 0xd8, 0x84, 0x46, 0x71, 0xda, 0xd7, 0xd0, 0x78, 0xdb, 0xe2, 0x04, 0x9f, 0x84, 0xfe,
	0x03, 0xd9, 0x0b, 0x3f, 0x40, 0x77, 0xc0, 0xd4, 0xa0, 0xba, 0x64, 0x63, 0xd6, 0x0c, 0xf0, 0x9a,
	0xa9, 0x01, 0xf9, 0x1b, 0x56, 0xf5, 0x4d, 0x4c, 0x2d, 0x5b, 0x2a, 0xa3, 0x6f, 0x0c, 0x51, 0xfb,
	0x94, 0x82, 0x02, 0xc5, 0x51, 0xab, 0xa7, 0xfd, 0x2b, 0xa6, 0xd1, 0x6b, 0xb7, 0xc9, 0x7f, 0x90,
	0x13, 0x4d, 0x31, 0xa3, 0x0c, 0x44, 0x53, 0x4c, 0x2a, 0xfd, 0x0b, 0xe6, 0x9f, 0x2b, 0xa2, 0xee,
	0x25, 0xde, 0x26, 0x72, 0xb2, 0xa2, 0x29, 0xda, 0x16, 0x20, 0x75, 0x28, 0xf3, 0x31, 0x0f, 0xd1,
	0x0d, 0xfc, 0xa1, 0xaf, 0xdd, 0xde, 0x80, 0x85, 0x7d, 0x54, 0x89, 0xa4, 0x0d, 0x4b, 0x9d, 0x1a,
	0xe6, 0x28, 0x26, 0xe6, 0x6a, 0x23, 0x3b, 0x50, 0xf4, 0x43, 0x5f, 0xfb, 0x2c, 0x70, 0x3d, 0x14,
	0x5c, 0xf9, 0xba, 0xba, 0x62, 0x03, 0x0a, 0x09, 0x7c, 0x1c, 0xa3, 0xb5, 0xf1, 0x74, 0x0f, 0xce,
	0x02, 0x3d, 0xcc, 0x11, 0x99, 0x5e, 0x40, 0xe4, 0xd2, 0x94, 0x81, 0xcf, 0xa1, 0x40, 0x95, 0xb8,
	0xef, 0xdf, 0xff, 0x90, 0x91, 0x76, 0x26, 0x6c, 0xd9, 0x5c, 0xb3, 0x30, 0x3d, 0x29, 0x34, 0x61,
	0x6b, 0x1f, 0xd3, 0x50, 0xa6, 0x38, 0xea, 0x08, 0xcf, 0x24, 0x26, 0xbd, 0xb4, 0x7f, 0xa2, 0x76,
	0xb2, 0x05, 0xeb, 0x89, 0xb1, 0xae, 0x87, 0x81, 0x66, 0x89, 0xff, 0xf9, 0x04, 0x3c, 0x36, 0x98,
	0x39, 0x85, 0x5e, 0x24, 0x25, 0x86, 0x7a, 0xf6, 0x14, 0x12, 0x38, 0x51, 0x4e, 0x9e, 0xc2, 0x5f,
	0xec, 0x8a, 0xf9, 0x01, 0xeb, 0x06, 0xe8, 0x6a, 0x7e, 0x89, 0xa1, 0xdb, 0xc5, 0x0b, 0x2e, 0xb1,
	0x9a, 0xb1, 0xf1, 0x7f, 0xde, 0xb1, 0xe7, 0x86, 0x3c, 0xb4, 0x1c, 0x69, 0x42, 0x65, 0x36, 0x8b,
	0x5d, 0x68, 0x94, 0xd5, 0x55, 0x9b, 0x54, 0x9e, 0x4e, 0x6a, 0x19, 0xea, 0x61, 0xe7, 0x9c, 0xdf,
	0xce, 0x7d, 0xdf, 0xb9, 0x53, 0x28, 0x51, 0x1c, 0x1d, 0x23, 0x7b, 0xcc, 0xf7, 0x7e, 0xcf, 0x85,
	0xf4, 0xd4, 0xec, 0x7f, 0x8e, 0x2f, 0x8f, 0x4e, 0xd8, 0xe5, 0xa1, 0xe7, 0x87, 0xfd, 0x1f, 0x31,
	0xbc, 0x4d, 0xa8, 0x44, 0x93, 0xfd, 0xdd, 0x21, 0xd3, 0x91, 0x44, 0x57, 0xfb, 0x43, 0x4c, 0x0e,
	0xa4, 0x7c, 0x47, 0x9e, 0x59, 0xee, 0xdc, 0x1f, 0xe2, 0xfc, 0x1b, 0x65, 0x1f, 0x36, 0x26, 0xc7,
	0xa6, 0xb9, 0x2b, 0x71, 0xc8, 0xaf, 0x30, 0x39, 0x93, 0x62, 0x42, 0x9c, 0x73, 0x6a, 0xe1, 0x6f,
	0x9a, 0x73, 0x7e, 0xa5, 0xe6, 0xde, 0xa7, 0xa0, 0x42, 0x71, 0xf4, 0xd6, 0xd7, 0x03, 0x4f, 0xb2,
	0xeb, 0xf0, 0x11, 0xdf, 0xd0, 0x5c, 0xcd, 0xe9, 0x85, 0x34, 0x4f, 0xdf, 0x9e, 0x2f, 0xa1, 0x42,
	0x95, 0x78, 0x40, 0xc6, 0xa2, 0x97, 0xe8, 0xc1, 0xec, 0x40, 0x2f, 0xd0, 0x42, 0xed, 0x05, 0x94,
	0xa8, 0x12, 0xd3, 0x49, 0x8b, 0x16, 0x1c, 0x01, 0x50, 0x1c, 0xb5, 0x25, 0x0a, 0xe6, 0x7b, 0x64,
	0x1b, 0x0a, 0xd7, 0x2c, 0x08, 0x50, 0xcf, 0x54, 0x5b, 0x8f, 0xd1, 0x89, 0x67, 0x5b, 0xb0, 0x2e,
	0x22, 0xd9, 0x1b, 0x30, 0x85, 0x9e, 0x1b, 0xf1, 0x71, 0xe2, 0x55, 0xfe, 0x0e, 0xec, 0xf0, 0xf1,
	0x7c, 0x93, 0x9e, 0x41, 0x9e, 0x9a, 0xa7, 0xc9, 0x19, 0x2a, 0xc5, 0xfa, 0x48, 0x08, 0x2c, 0xeb,
	0x5b, 0x81, 0x49, 0x29, 0xbb, 0x36, 0x98, 0xc7, 0x34, 0xb3, 0x1b, 0xe7, 0xa9, 0x5d, 0xef, 0x3f,
	0x81, 0xdc, 0xbd, 0xc7, 0x09, 0x29, 0x42, 0x8e, 0x9e, 0x38, 0xae, 0xd3, 0x39, 0x3a, 0x3a, 0x71,
	0x9c, 0xd2, 0x1f, 0x24, 0x0f, 0x6b, 0x06, 0x78, 0xd5, 0x7a, 0x73, 0x5a, 0x4a, 0x1d, 0xee, 0xbc,
	0xdb, 0xee, 0xfb, 0x7a, 0x10, 0x75, 0xeb, 0x3d, 0x3e, 0x6c, 0x28, 0x2d, 0x99, 0xe6, 0x2a, 0x44,
	0xdd, 0x50, 0x9e, 0x6a, 0xd8, 0xa7, 0x51, 0xc3, 0x54, 0x52, 0xdd, 0xf8, 0x69, 0x74, 0xf0, 0x25,
	0x00, 0x00, 0xff, 0xff, 0x25, 0xdf, 0x1c, 0x27, 0x30, 0x09, 0x00, 0x00,
}
