Port: :18081
NetworkAddress: 127.0.0.1
SPNetAddress: 127.0.0.1:8888
Debug: true
PPListDir: "./peers/pp-list"
AccountDir: "./account"
scryptN: 4096
scryptP: 6
DefPassword:
DefSavePath:
StorehousePath:
DownloadPath:
Password: aaa
Account: st1c7yf8ca7acazqfyp85q25249gr9zgewe03xylp
AutoRun: true
Internal: true
IsWallet: false
BPURL:
IsCheckDefaultPath:
IsLimitDownloadSpeed: true
LimitDownloadSpeed: 100
IsLimitUploadSpeed: true
LimitUploadSpeed: 100
IsCheckFileOperation:
IsCheckFileTransferFinished:
AddressPrefix: "st"
ChainId: "test-chain-localnet"
Token: "stos"
StratosChainAddress: 127.0.0.1
StratosChainPort: 1317
