Port: :18081
NetworkAddress: 127.0.0.1
SPNetworkId: sdm://0431341a51afc3241fc96017dcaddf87121737e18c0fefbb9f5ccdc56a3d4515a343c3ea09e9a36524a4b3618251f5eb049e54ad6f9aa37d2f3a6eb94d6ae4c1b5@127.0.0.1:8888
Debug: true
PPListDir: "./peers/pp-list"
AccountDir: "./account"
scryptN: 4096
scryptP: 6
DefPassword:
DefSavePath:
StorehousePath:
DownloadPath:
Password: aaa
Account: st145p208zkkha67sr2r0u28y3ncuk6hf2xkgkj69
AutoRun: true
Internal: true
IsWallet: false
BPURL:
IsCheckDefaultPath:
IsLimitDownloadSpeed: true
LimitDownloadSpeed: 100
IsLimitUploadSpeed: true
LimitUploadSpeed: 100
IsCheckFileOperation:
IsCheckFileTransferFinished:
AddressPrefix: "st"
ChainId: "test-chain"
Token: "stos"
StratosChainAddress: 127.0.0.1
StratosChainPort: 1317
