// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sds_comm.proto

/*
Package protos is a generated protocol buffer package.

j

It is generated from these files:
	sds_comm.proto
	sds.proto

It has these top-level messages:
	Result
	PPBaseInfo
	FileInfo
	SliceNumAddr
	SliceOffsetInfo
	SliceOffset
	FileIndexes
	DownloadSliceInfo
	SliceStorageInfo
	ShareLinkInfo
	AlbumInfo
	AlbumNumber
	ReqGetPPList
	RspGetPPList
	ReqRegister
	RspRegister
	ReqMining
	RspMining
	ReqUploadFile
	RspUploadFile
	ReqUploadFileSlice
	RspUploadFileSlice
	UploadSpeedOfProgress
	ReportUploadSliceResult
	RspReportUploadSliceResult
	ReqFindMyFileList
	RspFindMyFileList
	ReqFindDirectoryTree
	RspFindDirectoryTree
	ReqFileStorageInfo
	RspFileStorageInfo
	ReqDownloadSlice
	RspDownloadSlice
	ReqDownloadSliceWrong
	RspDownloadSliceWrong
	ReqDownloadSlicePause
	RspDownloadSlicePause
	ReqReportDownloadResult
	RspReportDownloadResult
	ReqReportTaskBP
	ReqRegisterNewPP
	RspRegisterNewPP
	ReqActivate
	RspActivate
	ReqActivated
	RspActivated
	ReqDeactivate
	RspDeactivate
	ReqDeactivated
	RspDeactivated
	ReqDeleteFile
	RspDeleteFile
	ReqTransferNotice
	RspTransferNotice
	ReqValidateTransferCer
	RspValidateTransferCer
	ReqTransferDownload
	RspTransferDownload
	RspTransferDownloadResult
	ReqReportTransferResult
	RspReportTransferResult
	ReqGetHDInfo
	RspGetHDInfo
	ReqSendChatMessages
	RspSendChatMessages
	ReqDeleteSlice
	RspDeleteSlice
	ReqMakeDirectory
	RspMakeDirectory
	ReqRemoveDirectory
	RspRemoveDirectory
	ReqMoveFileDirectory
	RspMoveFileDirectory
	ReqBLSPublicKey
	RspBPBLSPublicKey
	ReqBalance
	RspBalance
	ReqTransaction
	RspTransaction
	ReqBlockInfo
	RspBlockInfo
	ReqBlockCheck
	RspBlockCheck
	BlockCheckInfo
	ReqDownloadTaskInfo
	RspDownloadTaskInfo
	ReqShareLink
	RspShareLink
	ReqShareFile
	RspShareFile
	ReqDeleteShare
	RspDeleteShare
	ReqGetShareFile
	RspGetShareFile
	ReqSaveFile
	RspSaveFile
	ReqSaveFolder
	RspSaveFolder
	ReqCreateAlbum
	RspCreateAlbum
	ReqEditAlbum
	RspEditAlbum
	ReqAlbumContent
	RspAlbumContent
	ReqSearchAlbum
	RspSearchAlbum
	ReqFindMyAlbum
	RspFindMyAlbum
	ReqCollectionAlbum
	RspCollectionAlbum
	ReqAbstractAlbum
	RspAbstractAlbum
	ReqMyCollectionAlbum
	RspMyCollectionAlbum
	ReqDeleteAlbum
	RspDeleteAlbum
	ReqConfig
	RspConfig
	ReqInvite
	RspInvite
	ReqGetReward
	RspGetReward
	ReqGetCapacity
	RspGetCapacity
	ReqFileSort
	RspFileSort
	ReqFindDirectory
	RspFindDirectory
	ReqCustomerAddVolume
	RspCustomerAddVolume
	ReqCustomerUseVolume
	RspCustomerUseVolume
	RelayMessage
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResultState int32

const (
	ResultState_RES_SUCCESS ResultState = 0
	ResultState_RES_FAIL    ResultState = 1
)

var ResultState_name = map[int32]string{
	0: "RES_SUCCESS",
	1: "RES_FAIL",
}
var ResultState_value = map[string]int32{
	"RES_SUCCESS": 0,
	"RES_FAIL":    1,
}

func (x ResultState) String() string {
	return proto.EnumName(ResultState_name, int32(x))
}
func (ResultState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DownloadWrongType int32

const (
	DownloadWrongType_LOSESLICE DownloadWrongType = 0
	DownloadWrongType_OVERTIME  DownloadWrongType = 1
)

var DownloadWrongType_name = map[int32]string{
	0: "LOSESLICE",
	1: "OVERTIME",
}
var DownloadWrongType_value = map[string]int32{
	"LOSESLICE": 0,
	"OVERTIME":  1,
}

func (x DownloadWrongType) String() string {
	return proto.EnumName(DownloadWrongType_name, int32(x))
}
func (DownloadWrongType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type AlbumType int32

const (
	AlbumType_ALL   AlbumType = 0
	AlbumType_VIDEO AlbumType = 1
	AlbumType_MUSIC AlbumType = 2
	AlbumType_OTHER AlbumType = 3
)

var AlbumType_name = map[int32]string{
	0: "ALL",
	1: "VIDEO",
	2: "MUSIC",
	3: "OTHER",
}
var AlbumType_value = map[string]int32{
	"ALL":   0,
	"VIDEO": 1,
	"MUSIC": 2,
	"OTHER": 3,
}

func (x AlbumType) String() string {
	return proto.EnumName(AlbumType_name, int32(x))
}
func (AlbumType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type AlbumSortType int32

const (
	AlbumSortType_LATEST AlbumSortType = 0
	AlbumSortType_VISITS AlbumSortType = 1
)

var AlbumSortType_name = map[int32]string{
	0: "LATEST",
	1: "VISITS",
}
var AlbumSortType_value = map[string]int32{
	"LATEST": 0,
	"VISITS": 1,
}

func (x AlbumSortType) String() string {
	return proto.EnumName(AlbumSortType_name, int32(x))
}
func (AlbumSortType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type FileSortType int32

const (
	FileSortType_DEF  FileSortType = 0
	FileSortType_TIME FileSortType = 1
	FileSortType_SIZE FileSortType = 2
	FileSortType_NAME FileSortType = 3
)

var FileSortType_name = map[int32]string{
	0: "DEF",
	1: "TIME",
	2: "SIZE",
	3: "NAME",
}
var FileSortType_value = map[string]int32{
	"DEF":  0,
	"TIME": 1,
	"SIZE": 2,
	"NAME": 3,
}

func (x FileSortType) String() string {
	return proto.EnumName(FileSortType_name, int32(x))
}
func (FileSortType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type MsgType int32

const (
	MsgType_DEFAULT MsgType = 0
)

var MsgType_name = map[int32]string{
	0: "DEFAULT",
}
var MsgType_value = map[string]int32{
	"DEFAULT": 0,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}
func (MsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Result struct {
	State ResultState `protobuf:"varint,1,opt,name=state,enum=protos.ResultState" json:"state,omitempty"`
	Msg   string      `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Result) GetState() ResultState {
	if m != nil {
		return m.State
	}
	return ResultState_RES_SUCCESS
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PPBaseInfo struct {
	WalletAddress  string `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress" json:"wallet_address,omitempty"`
	NetworkAddress string `protobuf:"bytes,2,opt,name=network_address,json=networkAddress" json:"network_address,omitempty"`
}

func (m *PPBaseInfo) Reset()                    { *m = PPBaseInfo{} }
func (m *PPBaseInfo) String() string            { return proto.CompactTextString(m) }
func (*PPBaseInfo) ProtoMessage()               {}
func (*PPBaseInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PPBaseInfo) GetWalletAddress() string {
	if m != nil {
		return m.WalletAddress
	}
	return ""
}

func (m *PPBaseInfo) GetNetworkAddress() string {
	if m != nil {
		return m.NetworkAddress
	}
	return ""
}

type FileInfo struct {
	FileSize           uint64 `protobuf:"varint,1,opt,name=file_size,json=fileSize" json:"file_size,omitempty"`
	FileHash           string `protobuf:"bytes,2,opt,name=file_hash,json=fileHash" json:"file_hash,omitempty"`
	FileName           string `protobuf:"bytes,3,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
	CreateTime         uint64 `protobuf:"varint,4,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	IsDirectory        bool   `protobuf:"varint,5,opt,name=is_directory,json=isDirectory" json:"is_directory,omitempty"`
	StoragePath        string `protobuf:"bytes,6,opt,name=storage_path,json=storagePath" json:"storage_path,omitempty"`
	IsPrivate          bool   `protobuf:"varint,7,opt,name=is_private,json=isPrivate" json:"is_private,omitempty"`
	OwnerWalletAddress string `protobuf:"bytes,8,opt,name=owner_wallet_address,json=ownerWalletAddress" json:"owner_wallet_address,omitempty"`
	ShareLink          string `protobuf:"bytes,9,opt,name=share_link,json=shareLink" json:"share_link,omitempty"`
	SortId             uint64 `protobuf:"varint,10,opt,name=sort_id,json=sortId" json:"sort_id,omitempty"`
	Duration           uint64 `protobuf:"varint,11,opt,name=duration" json:"duration,omitempty"`
}

func (m *FileInfo) Reset()                    { *m = FileInfo{} }
func (m *FileInfo) String() string            { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()               {}
func (*FileInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FileInfo) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *FileInfo) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *FileInfo) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FileInfo) GetCreateTime() uint64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *FileInfo) GetIsDirectory() bool {
	if m != nil {
		return m.IsDirectory
	}
	return false
}

func (m *FileInfo) GetStoragePath() string {
	if m != nil {
		return m.StoragePath
	}
	return ""
}

func (m *FileInfo) GetIsPrivate() bool {
	if m != nil {
		return m.IsPrivate
	}
	return false
}

func (m *FileInfo) GetOwnerWalletAddress() string {
	if m != nil {
		return m.OwnerWalletAddress
	}
	return ""
}

func (m *FileInfo) GetShareLink() string {
	if m != nil {
		return m.ShareLink
	}
	return ""
}

func (m *FileInfo) GetSortId() uint64 {
	if m != nil {
		return m.SortId
	}
	return 0
}

func (m *FileInfo) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

// slice number and pp address
type SliceNumAddr struct {
	SliceNumber uint64       `protobuf:"varint,1,opt,name=slice_number,json=sliceNumber" json:"slice_number,omitempty"`
	SliceOffset *SliceOffset `protobuf:"bytes,2,opt,name=slice_offset,json=sliceOffset" json:"slice_offset,omitempty"`
	PpInfo      *PPBaseInfo  `protobuf:"bytes,3,opt,name=pp_info,json=ppInfo" json:"pp_info,omitempty"`
}

func (m *SliceNumAddr) Reset()                    { *m = SliceNumAddr{} }
func (m *SliceNumAddr) String() string            { return proto.CompactTextString(m) }
func (*SliceNumAddr) ProtoMessage()               {}
func (*SliceNumAddr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SliceNumAddr) GetSliceNumber() uint64 {
	if m != nil {
		return m.SliceNumber
	}
	return 0
}

func (m *SliceNumAddr) GetSliceOffset() *SliceOffset {
	if m != nil {
		return m.SliceOffset
	}
	return nil
}

func (m *SliceNumAddr) GetPpInfo() *PPBaseInfo {
	if m != nil {
		return m.PpInfo
	}
	return nil
}

type SliceOffsetInfo struct {
	SliceHash   string       `protobuf:"bytes,1,opt,name=slice_hash,json=sliceHash" json:"slice_hash,omitempty"`
	SliceOffset *SliceOffset `protobuf:"bytes,2,opt,name=slice_offset,json=sliceOffset" json:"slice_offset,omitempty"`
}

func (m *SliceOffsetInfo) Reset()                    { *m = SliceOffsetInfo{} }
func (m *SliceOffsetInfo) String() string            { return proto.CompactTextString(m) }
func (*SliceOffsetInfo) ProtoMessage()               {}
func (*SliceOffsetInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SliceOffsetInfo) GetSliceHash() string {
	if m != nil {
		return m.SliceHash
	}
	return ""
}

func (m *SliceOffsetInfo) GetSliceOffset() *SliceOffset {
	if m != nil {
		return m.SliceOffset
	}
	return nil
}

type SliceOffset struct {
	SliceOffsetStart uint64 `protobuf:"varint,1,opt,name=slice_offset_start,json=sliceOffsetStart" json:"slice_offset_start,omitempty"`
	SliceOffsetEnd   uint64 `protobuf:"varint,2,opt,name=slice_offset_end,json=sliceOffsetEnd" json:"slice_offset_end,omitempty"`
}

func (m *SliceOffset) Reset()                    { *m = SliceOffset{} }
func (m *SliceOffset) String() string            { return proto.CompactTextString(m) }
func (*SliceOffset) ProtoMessage()               {}
func (*SliceOffset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SliceOffset) GetSliceOffsetStart() uint64 {
	if m != nil {
		return m.SliceOffsetStart
	}
	return 0
}

func (m *SliceOffset) GetSliceOffsetEnd() uint64 {
	if m != nil {
		return m.SliceOffsetEnd
	}
	return 0
}

type FileIndexes struct {
	//  string file_hash = 1; // file hash
	FilePath      string `protobuf:"bytes,1,opt,name=file_path,json=filePath" json:"file_path,omitempty"`
	WalletAddress string `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress" json:"wallet_address,omitempty"`
	SavePath      string `protobuf:"bytes,3,opt,name=save_path,json=savePath" json:"save_path,omitempty"`
}

func (m *FileIndexes) Reset()                    { *m = FileIndexes{} }
func (m *FileIndexes) String() string            { return proto.CompactTextString(m) }
func (*FileIndexes) ProtoMessage()               {}
func (*FileIndexes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FileIndexes) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *FileIndexes) GetWalletAddress() string {
	if m != nil {
		return m.WalletAddress
	}
	return ""
}

func (m *FileIndexes) GetSavePath() string {
	if m != nil {
		return m.SavePath
	}
	return ""
}

type DownloadSliceInfo struct {
	SliceStorageInfo *SliceStorageInfo `protobuf:"bytes,1,opt,name=slice_storage_info,json=sliceStorageInfo" json:"slice_storage_info,omitempty"`
	SliceNumber      uint64            `protobuf:"varint,2,opt,name=slice_number,json=sliceNumber" json:"slice_number,omitempty"`
	StoragePpInfo    *PPBaseInfo       `protobuf:"bytes,3,opt,name=storage_pp_info,json=storagePpInfo" json:"storage_pp_info,omitempty"`
	BackupsPpInfo    *PPBaseInfo       `protobuf:"bytes,4,opt,name=backups_pp_info,json=backupsPpInfo" json:"backups_pp_info,omitempty"`
	VisitResult      bool              `protobuf:"varint,5,opt,name=visit_result,json=visitResult" json:"visit_result,omitempty"`
	TaskId           string            `protobuf:"bytes,6,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	SliceOffset      *SliceOffset      `protobuf:"bytes,7,opt,name=slice_offset,json=sliceOffset" json:"slice_offset,omitempty"`
}

func (m *DownloadSliceInfo) Reset()                    { *m = DownloadSliceInfo{} }
func (m *DownloadSliceInfo) String() string            { return proto.CompactTextString(m) }
func (*DownloadSliceInfo) ProtoMessage()               {}
func (*DownloadSliceInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DownloadSliceInfo) GetSliceStorageInfo() *SliceStorageInfo {
	if m != nil {
		return m.SliceStorageInfo
	}
	return nil
}

func (m *DownloadSliceInfo) GetSliceNumber() uint64 {
	if m != nil {
		return m.SliceNumber
	}
	return 0
}

func (m *DownloadSliceInfo) GetStoragePpInfo() *PPBaseInfo {
	if m != nil {
		return m.StoragePpInfo
	}
	return nil
}

func (m *DownloadSliceInfo) GetBackupsPpInfo() *PPBaseInfo {
	if m != nil {
		return m.BackupsPpInfo
	}
	return nil
}

func (m *DownloadSliceInfo) GetVisitResult() bool {
	if m != nil {
		return m.VisitResult
	}
	return false
}

func (m *DownloadSliceInfo) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *DownloadSliceInfo) GetSliceOffset() *SliceOffset {
	if m != nil {
		return m.SliceOffset
	}
	return nil
}

type SliceStorageInfo struct {
	SliceSize uint64 `protobuf:"varint,1,opt,name=slice_size,json=sliceSize" json:"slice_size,omitempty"`
	SliceHash string `protobuf:"bytes,2,opt,name=slice_hash,json=sliceHash" json:"slice_hash,omitempty"`
}

func (m *SliceStorageInfo) Reset()                    { *m = SliceStorageInfo{} }
func (m *SliceStorageInfo) String() string            { return proto.CompactTextString(m) }
func (*SliceStorageInfo) ProtoMessage()               {}
func (*SliceStorageInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SliceStorageInfo) GetSliceSize() uint64 {
	if m != nil {
		return m.SliceSize
	}
	return 0
}

func (m *SliceStorageInfo) GetSliceHash() string {
	if m != nil {
		return m.SliceHash
	}
	return ""
}

type ShareLinkInfo struct {
	Name               string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	FileHash           string `protobuf:"bytes,2,opt,name=file_hash,json=fileHash" json:"file_hash,omitempty"`
	LinkTime           uint64 `protobuf:"varint,3,opt,name=link_time,json=linkTime" json:"link_time,omitempty"`
	FileSize           uint64 `protobuf:"varint,4,opt,name=file_size,json=fileSize" json:"file_size,omitempty"`
	LinkTimeExp        uint64 `protobuf:"varint,5,opt,name=link_time_exp,json=linkTimeExp" json:"link_time_exp,omitempty"`
	ShareId            string `protobuf:"bytes,6,opt,name=share_id,json=shareId" json:"share_id,omitempty"`
	IsDirectory        bool   `protobuf:"varint,7,opt,name=is_directory,json=isDirectory" json:"is_directory,omitempty"`
	ShareLink          string `protobuf:"bytes,8,opt,name=share_link,json=shareLink" json:"share_link,omitempty"`
	IsPrivate          bool   `protobuf:"varint,9,opt,name=is_private,json=isPrivate" json:"is_private,omitempty"`
	ShareLinkPassword  string `protobuf:"bytes,10,opt,name=share_link_password,json=shareLinkPassword" json:"share_link_password,omitempty"`
	OwnerWalletAddress string `protobuf:"bytes,11,opt,name=owner_wallet_address,json=ownerWalletAddress" json:"owner_wallet_address,omitempty"`
}

func (m *ShareLinkInfo) Reset()                    { *m = ShareLinkInfo{} }
func (m *ShareLinkInfo) String() string            { return proto.CompactTextString(m) }
func (*ShareLinkInfo) ProtoMessage()               {}
func (*ShareLinkInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ShareLinkInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ShareLinkInfo) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *ShareLinkInfo) GetLinkTime() uint64 {
	if m != nil {
		return m.LinkTime
	}
	return 0
}

func (m *ShareLinkInfo) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *ShareLinkInfo) GetLinkTimeExp() uint64 {
	if m != nil {
		return m.LinkTimeExp
	}
	return 0
}

func (m *ShareLinkInfo) GetShareId() string {
	if m != nil {
		return m.ShareId
	}
	return ""
}

func (m *ShareLinkInfo) GetIsDirectory() bool {
	if m != nil {
		return m.IsDirectory
	}
	return false
}

func (m *ShareLinkInfo) GetShareLink() string {
	if m != nil {
		return m.ShareLink
	}
	return ""
}

func (m *ShareLinkInfo) GetIsPrivate() bool {
	if m != nil {
		return m.IsPrivate
	}
	return false
}

func (m *ShareLinkInfo) GetShareLinkPassword() string {
	if m != nil {
		return m.ShareLinkPassword
	}
	return ""
}

func (m *ShareLinkInfo) GetOwnerWalletAddress() string {
	if m != nil {
		return m.OwnerWalletAddress
	}
	return ""
}

type AlbumInfo struct {
	AlbumId        string    `protobuf:"bytes,1,opt,name=album_id,json=albumId" json:"album_id,omitempty"`
	AlbumName      string    `protobuf:"bytes,2,opt,name=album_name,json=albumName" json:"album_name,omitempty"`
	AlbumBlurb     string    `protobuf:"bytes,3,opt,name=album_blurb,json=albumBlurb" json:"album_blurb,omitempty"`
	AlbumVisit     int64     `protobuf:"varint,4,opt,name=album_visit,json=albumVisit" json:"album_visit,omitempty"`
	AlbumTime      int64     `protobuf:"varint,5,opt,name=album_time,json=albumTime" json:"album_time,omitempty"`
	AlbumCoverLink string    `protobuf:"bytes,6,opt,name=album_cover_link,json=albumCoverLink" json:"album_cover_link,omitempty"`
	IsPrivate      bool      `protobuf:"varint,7,opt,name=is_private,json=isPrivate" json:"is_private,omitempty"`
	AlbumType      AlbumType `protobuf:"varint,8,opt,name=album_type,json=albumType,enum=protos.AlbumType" json:"album_type,omitempty"`
}

func (m *AlbumInfo) Reset()                    { *m = AlbumInfo{} }
func (m *AlbumInfo) String() string            { return proto.CompactTextString(m) }
func (*AlbumInfo) ProtoMessage()               {}
func (*AlbumInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *AlbumInfo) GetAlbumId() string {
	if m != nil {
		return m.AlbumId
	}
	return ""
}

func (m *AlbumInfo) GetAlbumName() string {
	if m != nil {
		return m.AlbumName
	}
	return ""
}

func (m *AlbumInfo) GetAlbumBlurb() string {
	if m != nil {
		return m.AlbumBlurb
	}
	return ""
}

func (m *AlbumInfo) GetAlbumVisit() int64 {
	if m != nil {
		return m.AlbumVisit
	}
	return 0
}

func (m *AlbumInfo) GetAlbumTime() int64 {
	if m != nil {
		return m.AlbumTime
	}
	return 0
}

func (m *AlbumInfo) GetAlbumCoverLink() string {
	if m != nil {
		return m.AlbumCoverLink
	}
	return ""
}

func (m *AlbumInfo) GetIsPrivate() bool {
	if m != nil {
		return m.IsPrivate
	}
	return false
}

func (m *AlbumInfo) GetAlbumType() AlbumType {
	if m != nil {
		return m.AlbumType
	}
	return AlbumType_ALL
}

type AlbumNumber struct {
	All   int64 `protobuf:"varint,1,opt,name=all" json:"all,omitempty"`
	Video int64 `protobuf:"varint,2,opt,name=video" json:"video,omitempty"`
	Music int64 `protobuf:"varint,3,opt,name=music" json:"music,omitempty"`
	Other int64 `protobuf:"varint,4,opt,name=other" json:"other,omitempty"`
}

func (m *AlbumNumber) Reset()                    { *m = AlbumNumber{} }
func (m *AlbumNumber) String() string            { return proto.CompactTextString(m) }
func (*AlbumNumber) ProtoMessage()               {}
func (*AlbumNumber) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *AlbumNumber) GetAll() int64 {
	if m != nil {
		return m.All
	}
	return 0
}

func (m *AlbumNumber) GetVideo() int64 {
	if m != nil {
		return m.Video
	}
	return 0
}

func (m *AlbumNumber) GetMusic() int64 {
	if m != nil {
		return m.Music
	}
	return 0
}

func (m *AlbumNumber) GetOther() int64 {
	if m != nil {
		return m.Other
	}
	return 0
}

func init() {
	proto.RegisterType((*Result)(nil), "protos.Result")
	proto.RegisterType((*PPBaseInfo)(nil), "protos.PPBaseInfo")
	proto.RegisterType((*FileInfo)(nil), "protos.FileInfo")
	proto.RegisterType((*SliceNumAddr)(nil), "protos.SliceNumAddr")
	proto.RegisterType((*SliceOffsetInfo)(nil), "protos.SliceOffsetInfo")
	proto.RegisterType((*SliceOffset)(nil), "protos.SliceOffset")
	proto.RegisterType((*FileIndexes)(nil), "protos.FileIndexes")
	proto.RegisterType((*DownloadSliceInfo)(nil), "protos.DownloadSliceInfo")
	proto.RegisterType((*SliceStorageInfo)(nil), "protos.SliceStorageInfo")
	proto.RegisterType((*ShareLinkInfo)(nil), "protos.ShareLinkInfo")
	proto.RegisterType((*AlbumInfo)(nil), "protos.AlbumInfo")
	proto.RegisterType((*AlbumNumber)(nil), "protos.AlbumNumber")
	proto.RegisterEnum("protos.ResultState", ResultState_name, ResultState_value)
	proto.RegisterEnum("protos.DownloadWrongType", DownloadWrongType_name, DownloadWrongType_value)
	proto.RegisterEnum("protos.AlbumType", AlbumType_name, AlbumType_value)
	proto.RegisterEnum("protos.AlbumSortType", AlbumSortType_name, AlbumSortType_value)
	proto.RegisterEnum("protos.FileSortType", FileSortType_name, FileSortType_value)
	proto.RegisterEnum("protos.MsgType", MsgType_name, MsgType_value)
}

func init() { proto.RegisterFile("sds_comm.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0x8e, 0x2d, 0xc7, 0xb2, 0x8e, 0x62, 0x47, 0x65, 0x8b, 0xd5, 0x5d, 0x51, 0xac, 0x15, 0x30,
	0x34, 0xcb, 0x8a, 0xa2, 0xc8, 0xb0, 0x5d, 0xec, 0xce, 0x4d, 0x14, 0x54, 0x80, 0x93, 0x18, 0x92,
	0x93, 0x02, 0xc3, 0x00, 0x81, 0xb6, 0x98, 0x98, 0x88, 0x2c, 0x09, 0xa4, 0x9c, 0x9f, 0x3e, 0xc8,
	0xee, 0xf7, 0x7a, 0x03, 0xf6, 0x06, 0xbb, 0x18, 0x78, 0x28, 0xf9, 0x37, 0x41, 0x87, 0x5d, 0x99,
	0xfc, 0xce, 0x0f, 0xc9, 0xef, 0x9c, 0xf3, 0x59, 0xd0, 0x91, 0xb1, 0x8c, 0xc6, 0xd9, 0x74, 0xfa,
	0x3e, 0x17, 0x59, 0x91, 0x91, 0x26, 0xfe, 0x48, 0xd7, 0x83, 0x66, 0xc0, 0xe4, 0x2c, 0x29, 0xc8,
	0x0f, 0xb0, 0x2d, 0x0b, 0x5a, 0xb0, 0x6e, 0xed, 0x75, 0x6d, 0xaf, 0x73, 0xf0, 0x54, 0x3b, 0xca,
	0xf7, 0xda, 0x1c, 0x2a, 0x53, 0xa0, 0x3d, 0x88, 0x03, 0xc6, 0x54, 0x5e, 0x75, 0xeb, 0xaf, 0x6b,
	0x7b, 0x56, 0xa0, 0x96, 0xee, 0xef, 0x00, 0x83, 0xc1, 0x47, 0x2a, 0x99, 0x9f, 0x5e, 0x66, 0xe4,
	0x7b, 0xe8, 0xdc, 0xd2, 0x24, 0x61, 0x45, 0x44, 0xe3, 0x58, 0x30, 0x29, 0x31, 0xa7, 0x15, 0xb4,
	0x35, 0xda, 0xd3, 0x20, 0x79, 0x0b, 0xbb, 0x29, 0x2b, 0x6e, 0x33, 0x71, 0x3d, 0xf7, 0xd3, 0x29,
	0x3b, 0x25, 0x5c, 0x3a, 0xba, 0x7f, 0xd7, 0xa1, 0x75, 0xcc, 0x13, 0x9d, 0xfc, 0x25, 0x58, 0x97,
	0x3c, 0x61, 0x91, 0xe4, 0x5f, 0xf4, 0x5d, 0x1b, 0x41, 0x4b, 0x01, 0x21, 0xff, 0xc2, 0xe6, 0xc6,
	0x09, 0x95, 0x93, 0x32, 0x19, 0x1a, 0x3f, 0x51, 0x39, 0x99, 0x1b, 0x53, 0x3a, 0x65, 0x5d, 0x63,
	0x61, 0x3c, 0xa5, 0x53, 0x46, 0xbe, 0x03, 0x7b, 0x2c, 0x18, 0x2d, 0x58, 0x54, 0xf0, 0x29, 0xeb,
	0x36, 0x30, 0x31, 0x68, 0x68, 0xc8, 0xa7, 0x8c, 0xbc, 0x81, 0x1d, 0x2e, 0xa3, 0x98, 0x0b, 0x36,
	0x2e, 0x32, 0x71, 0xdf, 0xdd, 0x7e, 0x5d, 0xdb, 0x6b, 0x05, 0x36, 0x97, 0x47, 0x15, 0xa4, 0x5c,
	0x64, 0x91, 0x09, 0x7a, 0xc5, 0xa2, 0x9c, 0x16, 0x93, 0x6e, 0x13, 0xcf, 0xb0, 0x4b, 0x6c, 0x40,
	0x8b, 0x09, 0x79, 0x05, 0xc0, 0x65, 0x94, 0x0b, 0x7e, 0xa3, 0xa8, 0x36, 0x31, 0x87, 0xc5, 0xe5,
	0x40, 0x03, 0xe4, 0x03, 0x3c, 0xcb, 0x6e, 0x53, 0x26, 0xa2, 0x35, 0xfe, 0x5a, 0x98, 0x89, 0xa0,
	0xed, 0xf3, 0x0a, 0x89, 0xaf, 0x00, 0xe4, 0x84, 0x0a, 0x16, 0x25, 0x3c, 0xbd, 0xee, 0x5a, 0xe8,
	0x67, 0x21, 0xd2, 0xe7, 0xe9, 0x35, 0x79, 0x0e, 0xa6, 0xcc, 0x44, 0x11, 0xf1, 0xb8, 0x0b, 0xf8,
	0xa4, 0xa6, 0xda, 0xfa, 0x31, 0xf9, 0x16, 0x5a, 0xf1, 0x4c, 0xd0, 0x82, 0x67, 0x69, 0xd7, 0xd6,
	0x2c, 0x56, 0x7b, 0xf7, 0x8f, 0x1a, 0xec, 0x84, 0x09, 0x1f, 0xb3, 0xd3, 0xd9, 0x54, 0x9d, 0x83,
	0x0f, 0x53, 0xfb, 0x28, 0x9d, 0x4d, 0x47, 0x4c, 0x94, 0xb4, 0xdb, 0xb2, 0xf4, 0x19, 0x31, 0x41,
	0x7e, 0xa9, 0x5c, 0xb2, 0xcb, 0x4b, 0xc9, 0x0a, 0x24, 0xdf, 0x5e, 0x74, 0x11, 0xa6, 0x3b, 0x43,
	0x53, 0x19, 0xa7, 0x37, 0xe4, 0x47, 0x30, 0xf3, 0x3c, 0xe2, 0xe9, 0x65, 0x86, 0x25, 0xb1, 0x0f,
	0x48, 0x15, 0xb2, 0x68, 0xa8, 0xa0, 0x99, 0xe7, 0xea, 0xd7, 0x9d, 0xc0, 0xee, 0x52, 0x22, 0x6c,
	0x07, 0xf5, 0x7e, 0x3c, 0x17, 0x4b, 0x5e, 0x2b, 0xdf, 0xaf, 0x10, 0xac, 0xf9, 0xff, 0xbc, 0x96,
	0xcb, 0xc0, 0x5e, 0xb2, 0x91, 0x77, 0x40, 0x96, 0xd3, 0x44, 0xb2, 0xa0, 0xa2, 0x28, 0x69, 0x70,
	0x96, 0xe2, 0x42, 0x85, 0x93, 0x3d, 0x70, 0x56, 0xbc, 0x59, 0x1a, 0xe3, 0xc1, 0x8d, 0xa0, 0xb3,
	0xe4, 0xeb, 0xa5, 0xb1, 0x9b, 0x82, 0xad, 0x1b, 0x3b, 0x66, 0x77, 0x4c, 0xce, 0x3b, 0x14, 0xbb,
	0xa7, 0xb6, 0xe8, 0x50, 0x6c, 0x9d, 0xcd, 0xa9, 0xaa, 0x3f, 0x34, 0x55, 0x2f, 0xc1, 0x92, 0xf4,
	0xa6, 0xcc, 0x51, 0x76, 0xb9, 0x02, 0x54, 0x0e, 0xf7, 0xaf, 0x3a, 0x3c, 0x39, 0xca, 0x6e, 0xd3,
	0x24, 0xa3, 0x31, 0xbe, 0x0f, 0x39, 0x3c, 0xae, 0x5e, 0x57, 0x75, 0x2f, 0x96, 0xa3, 0x86, 0x54,
	0x75, 0x57, 0xa8, 0x0a, 0xb5, 0x03, 0x16, 0x45, 0xbf, 0x71, 0x09, 0xd9, 0x68, 0x93, 0xfa, 0x66,
	0x9b, 0xfc, 0x0a, 0xbb, 0xf3, 0x11, 0xf9, 0x6a, 0xd9, 0xdb, 0xd5, 0xe4, 0x60, 0xf5, 0x55, 0xec,
	0x88, 0x8e, 0xaf, 0x67, 0xb9, 0x9c, 0xc7, 0x36, 0x1e, 0x8f, 0x2d, 0x5d, 0xcb, 0xd8, 0x37, 0xb0,
	0x73, 0xc3, 0x25, 0x2f, 0x22, 0x81, 0x72, 0x56, 0x4d, 0x2f, 0x62, 0xa5, 0x00, 0x3e, 0x07, 0xb3,
	0xa0, 0xf2, 0x5a, 0x8d, 0x8a, 0x1e, 0xdc, 0xa6, 0xda, 0xfa, 0xf1, 0x46, 0x0f, 0x99, 0xff, 0xb1,
	0x87, 0x06, 0xe0, 0xac, 0x93, 0xb6, 0x68, 0xd7, 0x25, 0xf9, 0xd2, 0xed, 0x8a, 0xfa, 0xb5, 0xda,
	0xcd, 0xf5, 0xb5, 0x6e, 0x76, 0xff, 0xa9, 0x43, 0x3b, 0xac, 0x66, 0x1b, 0xf3, 0x11, 0x68, 0xa0,
	0x9c, 0xe9, 0x66, 0xc1, 0xf5, 0x57, 0x45, 0x50, 0x29, 0x85, 0x56, 0x39, 0x43, 0x0f, 0xbe, 0x02,
	0x50, 0xe3, 0x56, 0xb4, 0xb5, 0xb1, 0xa6, 0xad, 0x2e, 0xb4, 0xe7, 0x91, 0x11, 0xbb, 0xcb, 0x91,
	0xc3, 0x46, 0x60, 0x57, 0xd1, 0xde, 0x5d, 0x4e, 0x5e, 0x40, 0x4b, 0xab, 0xd1, 0x9c, 0x44, 0x13,
	0xf7, 0x7e, 0xbc, 0xa1, 0x9f, 0xe6, 0xa6, 0x7e, 0xae, 0x6a, 0x59, 0x6b, 0x5d, 0xcb, 0x56, 0xb5,
	0xd3, 0x5a, 0xd7, 0xce, 0xf7, 0xf0, 0x74, 0x11, 0x1d, 0xe5, 0x54, 0xca, 0xdb, 0x4c, 0x68, 0xd9,
	0xb3, 0x82, 0x27, 0xf3, 0x34, 0x83, 0xd2, 0xf0, 0xa8, 0xd6, 0xda, 0x8f, 0x69, 0xad, 0xfb, 0x67,
	0x1d, 0xac, 0x5e, 0x32, 0x9a, 0x4d, 0x91, 0xfa, 0x17, 0xd0, 0xa2, 0x6a, 0xa3, 0xde, 0xaa, 0xe9,
	0x37, 0x71, 0xef, 0xc7, 0xea, 0xa6, 0xda, 0x84, 0xb5, 0x29, 0xcb, 0x88, 0x48, 0xf5, 0x5f, 0xa3,
	0xcd, 0xa3, 0x64, 0x26, 0x46, 0xe5, 0x90, 0xea, 0x88, 0x8f, 0x0a, 0x59, 0x38, 0x60, 0x7f, 0x62,
	0x25, 0x8c, 0xd2, 0xe1, 0x42, 0x21, 0x8b, 0x03, 0xb0, 0x8c, 0xdb, 0x68, 0xd7, 0x07, 0x60, 0x1d,
	0xf7, 0xc0, 0xd1, 0xe6, 0x71, 0x76, 0xc3, 0x84, 0xa6, 0x53, 0x97, 0xa3, 0x83, 0xf8, 0xa1, 0x82,
	0x1f, 0xe0, 0xf4, 0x81, 0xff, 0xa3, 0xea, 0x9c, 0xfb, 0x9c, 0x61, 0x45, 0x3a, 0x07, 0x4f, 0xaa,
	0xc6, 0x47, 0x2a, 0x86, 0xf7, 0x39, 0xab, 0x8e, 0xbe, 0xcf, 0x99, 0x4b, 0xc1, 0x46, 0xbc, 0x9c,
	0x77, 0x07, 0x0c, 0x9a, 0x24, 0xc8, 0x8f, 0x11, 0xa8, 0x25, 0x79, 0x06, 0xdb, 0x37, 0x3c, 0x66,
	0x19, 0xd2, 0x62, 0x04, 0x7a, 0xa3, 0xd0, 0xe9, 0x4c, 0xf2, 0x31, 0x92, 0x61, 0x04, 0x7a, 0xa3,
	0xd0, 0xac, 0x98, 0x30, 0x51, 0x32, 0xa0, 0x37, 0xfb, 0xef, 0xc0, 0x5e, 0xfa, 0x28, 0x21, 0xbb,
	0x60, 0x07, 0x5e, 0x18, 0x85, 0xe7, 0x87, 0x87, 0x5e, 0x18, 0x3a, 0x5b, 0x64, 0x07, 0x5a, 0x0a,
	0x38, 0xee, 0xf9, 0x7d, 0xa7, 0xb6, 0xff, 0x61, 0xa1, 0x78, 0x9f, 0x45, 0x96, 0x5e, 0xa9, 0x5b,
	0x92, 0x36, 0x58, 0xfd, 0xb3, 0xd0, 0x0b, 0xfb, 0xfe, 0xa1, 0xa7, 0x23, 0xce, 0x2e, 0xbc, 0x60,
	0xe8, 0x9f, 0x78, 0x4e, 0x6d, 0xff, 0xe7, 0xb2, 0xca, 0xe8, 0x69, 0x82, 0xd1, 0xeb, 0xf7, 0x9d,
	0x2d, 0x62, 0xc1, 0xf6, 0x85, 0x7f, 0xe4, 0x9d, 0x39, 0x35, 0xb5, 0x3c, 0x39, 0x0f, 0xfd, 0x43,
	0xa7, 0xae, 0x96, 0x67, 0xc3, 0x4f, 0x5e, 0xe0, 0x18, 0xfb, 0x6f, 0xa1, 0x8d, 0x61, 0x61, 0x26,
	0x0a, 0x0c, 0x05, 0x68, 0xf6, 0x7b, 0x43, 0x2f, 0x1c, 0x3a, 0x5b, 0x6a, 0x7d, 0xe1, 0x87, 0xfe,
	0x30, 0xc4, 0xfc, 0x3b, 0x4a, 0xf4, 0xe7, 0x7e, 0x26, 0x18, 0x47, 0xde, 0xb1, 0xb3, 0x45, 0x5a,
	0xd0, 0xd0, 0x57, 0x50, 0xab, 0xd0, 0xff, 0xcd, 0x73, 0xea, 0x6a, 0x75, 0xda, 0x3b, 0xf1, 0x1c,
	0x63, 0xff, 0x1b, 0x30, 0x4f, 0xa4, 0xbe, 0xbe, 0x0d, 0xe6, 0x91, 0x77, 0xdc, 0x3b, 0xef, 0x0f,
	0x9d, 0xad, 0x91, 0xfe, 0x94, 0xfb, 0xe9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x50, 0x22, 0x90,
	0xea, 0xe3, 0x09, 0x00, 0x00,
}
