// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sds_comm.proto

// j

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResultState int32

const (
	ResultState_RES_SUCCESS ResultState = 0
	ResultState_RES_FAIL    ResultState = 1
)

var ResultState_name = map[int32]string{
	0: "RES_SUCCESS",
	1: "RES_FAIL",
}

var ResultState_value = map[string]int32{
	"RES_SUCCESS": 0,
	"RES_FAIL":    1,
}

func (x ResultState) String() string {
	return proto.EnumName(ResultState_name, int32(x))
}

func (ResultState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_12078ceca3ea879d, []int{0}
}

type DownloadWrongType int32

const (
	DownloadWrongType_LOSESLICE DownloadWrongType = 0
	DownloadWrongType_OVERTIME  DownloadWrongType = 1
)

var DownloadWrongType_name = map[int32]string{
	0: "LOSESLICE",
	1: "OVERTIME",
}

var DownloadWrongType_value = map[string]int32{
	"LOSESLICE": 0,
	"OVERTIME":  1,
}

func (x DownloadWrongType) String() string {
	return proto.EnumName(DownloadWrongType_name, int32(x))
}

func (DownloadWrongType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_12078ceca3ea879d, []int{1}
}

type AlbumType int32

const (
	AlbumType_ALL   AlbumType = 0
	AlbumType_VIDEO AlbumType = 1
	AlbumType_MUSIC AlbumType = 2
	AlbumType_OTHER AlbumType = 3
)

var AlbumType_name = map[int32]string{
	0: "ALL",
	1: "VIDEO",
	2: "MUSIC",
	3: "OTHER",
}

var AlbumType_value = map[string]int32{
	"ALL":   0,
	"VIDEO": 1,
	"MUSIC": 2,
	"OTHER": 3,
}

func (x AlbumType) String() string {
	return proto.EnumName(AlbumType_name, int32(x))
}

func (AlbumType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_12078ceca3ea879d, []int{2}
}

type AlbumSortType int32

const (
	AlbumSortType_LATEST AlbumSortType = 0
	AlbumSortType_VISITS AlbumSortType = 1
)

var AlbumSortType_name = map[int32]string{
	0: "LATEST",
	1: "VISITS",
}

var AlbumSortType_value = map[string]int32{
	"LATEST": 0,
	"VISITS": 1,
}

func (x AlbumSortType) String() string {
	return proto.EnumName(AlbumSortType_name, int32(x))
}

func (AlbumSortType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_12078ceca3ea879d, []int{3}
}

type FileSortType int32

const (
	FileSortType_DEF  FileSortType = 0
	FileSortType_TIME FileSortType = 1
	FileSortType_SIZE FileSortType = 2
	FileSortType_NAME FileSortType = 3
)

var FileSortType_name = map[int32]string{
	0: "DEF",
	1: "TIME",
	2: "SIZE",
	3: "NAME",
}

var FileSortType_value = map[string]int32{
	"DEF":  0,
	"TIME": 1,
	"SIZE": 2,
	"NAME": 3,
}

func (x FileSortType) String() string {
	return proto.EnumName(FileSortType_name, int32(x))
}

func (FileSortType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_12078ceca3ea879d, []int{4}
}

type MsgType int32

const (
	MsgType_DEFAULT MsgType = 0
)

var MsgType_name = map[int32]string{
	0: "DEFAULT",
}

var MsgType_value = map[string]int32{
	"DEFAULT": 0,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_12078ceca3ea879d, []int{5}
}

type Result struct {
	State                ResultState `protobuf:"varint,1,opt,name=state,proto3,enum=protos.ResultState" json:"state,omitempty"`
	Msg                  string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_12078ceca3ea879d, []int{0}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetState() ResultState {
	if m != nil {
		return m.State
	}
	return ResultState_RES_SUCCESS
}

func (m *Result) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PPBaseInfo struct {
	P2PAddress           string   `protobuf:"bytes,1,opt,name=p2p_address,json=p2pAddress,proto3" json:"p2p_address,omitempty"`
	WalletAddress        string   `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	NetworkAddress       string   `protobuf:"bytes,3,opt,name=network_address,json=networkAddress,proto3" json:"network_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PPBaseInfo) Reset()         { *m = PPBaseInfo{} }
func (m *PPBaseInfo) String() string { return proto.CompactTextString(m) }
func (*PPBaseInfo) ProtoMessage()    {}
func (*PPBaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_12078ceca3ea879d, []int{1}
}

func (m *PPBaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PPBaseInfo.Unmarshal(m, b)
}
func (m *PPBaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PPBaseInfo.Marshal(b, m, deterministic)
}
func (m *PPBaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PPBaseInfo.Merge(m, src)
}
func (m *PPBaseInfo) XXX_Size() int {
	return xxx_messageInfo_PPBaseInfo.Size(m)
}
func (m *PPBaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PPBaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PPBaseInfo proto.InternalMessageInfo

func (m *PPBaseInfo) GetP2PAddress() string {
	if m != nil {
		return m.P2PAddress
	}
	return ""
}

func (m *PPBaseInfo) GetWalletAddress() string {
	if m != nil {
		return m.WalletAddress
	}
	return ""
}

func (m *PPBaseInfo) GetNetworkAddress() string {
	if m != nil {
		return m.NetworkAddress
	}
	return ""
}

type FileInfo struct {
	FileSize             uint64   `protobuf:"varint,1,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileHash             string   `protobuf:"bytes,2,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	FileName             string   `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	CreateTime           uint64   `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	IsDirectory          bool     `protobuf:"varint,5,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	StoragePath          string   `protobuf:"bytes,6,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	IsPrivate            bool     `protobuf:"varint,7,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	OwnerWalletAddress   string   `protobuf:"bytes,8,opt,name=owner_wallet_address,json=ownerWalletAddress,proto3" json:"owner_wallet_address,omitempty"`
	ShareLink            string   `protobuf:"bytes,9,opt,name=share_link,json=shareLink,proto3" json:"share_link,omitempty"`
	SortId               uint64   `protobuf:"varint,10,opt,name=sort_id,json=sortId,proto3" json:"sort_id,omitempty"`
	Duration             uint64   `protobuf:"varint,11,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_12078ceca3ea879d, []int{2}
}

func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (m *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(m, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *FileInfo) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *FileInfo) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *FileInfo) GetCreateTime() uint64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *FileInfo) GetIsDirectory() bool {
	if m != nil {
		return m.IsDirectory
	}
	return false
}

func (m *FileInfo) GetStoragePath() string {
	if m != nil {
		return m.StoragePath
	}
	return ""
}

func (m *FileInfo) GetIsPrivate() bool {
	if m != nil {
		return m.IsPrivate
	}
	return false
}

func (m *FileInfo) GetOwnerWalletAddress() string {
	if m != nil {
		return m.OwnerWalletAddress
	}
	return ""
}

func (m *FileInfo) GetShareLink() string {
	if m != nil {
		return m.ShareLink
	}
	return ""
}

func (m *FileInfo) GetSortId() uint64 {
	if m != nil {
		return m.SortId
	}
	return 0
}

func (m *FileInfo) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

// slice number and pp address
type SliceNumAddr struct {
	SliceNumber          uint64       `protobuf:"varint,1,opt,name=slice_number,json=sliceNumber,proto3" json:"slice_number,omitempty"`
	SliceOffset          *SliceOffset `protobuf:"bytes,2,opt,name=slice_offset,json=sliceOffset,proto3" json:"slice_offset,omitempty"`
	PpInfo               *PPBaseInfo  `protobuf:"bytes,3,opt,name=pp_info,json=ppInfo,proto3" json:"pp_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SliceNumAddr) Reset()         { *m = SliceNumAddr{} }
func (m *SliceNumAddr) String() string { return proto.CompactTextString(m) }
func (*SliceNumAddr) ProtoMessage()    {}
func (*SliceNumAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_12078ceca3ea879d, []int{3}
}

func (m *SliceNumAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SliceNumAddr.Unmarshal(m, b)
}
func (m *SliceNumAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SliceNumAddr.Marshal(b, m, deterministic)
}
func (m *SliceNumAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SliceNumAddr.Merge(m, src)
}
func (m *SliceNumAddr) XXX_Size() int {
	return xxx_messageInfo_SliceNumAddr.Size(m)
}
func (m *SliceNumAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_SliceNumAddr.DiscardUnknown(m)
}

var xxx_messageInfo_SliceNumAddr proto.InternalMessageInfo

func (m *SliceNumAddr) GetSliceNumber() uint64 {
	if m != nil {
		return m.SliceNumber
	}
	return 0
}

func (m *SliceNumAddr) GetSliceOffset() *SliceOffset {
	if m != nil {
		return m.SliceOffset
	}
	return nil
}

func (m *SliceNumAddr) GetPpInfo() *PPBaseInfo {
	if m != nil {
		return m.PpInfo
	}
	return nil
}

type SliceOffsetInfo struct {
	SliceHash            string       `protobuf:"bytes,1,opt,name=slice_hash,json=sliceHash,proto3" json:"slice_hash,omitempty"`
	SliceOffset          *SliceOffset `protobuf:"bytes,2,opt,name=slice_offset,json=sliceOffset,proto3" json:"slice_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SliceOffsetInfo) Reset()         { *m = SliceOffsetInfo{} }
func (m *SliceOffsetInfo) String() string { return proto.CompactTextString(m) }
func (*SliceOffsetInfo) ProtoMessage()    {}
func (*SliceOffsetInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_12078ceca3ea879d, []int{4}
}

func (m *SliceOffsetInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SliceOffsetInfo.Unmarshal(m, b)
}
func (m *SliceOffsetInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SliceOffsetInfo.Marshal(b, m, deterministic)
}
func (m *SliceOffsetInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SliceOffsetInfo.Merge(m, src)
}
func (m *SliceOffsetInfo) XXX_Size() int {
	return xxx_messageInfo_SliceOffsetInfo.Size(m)
}
func (m *SliceOffsetInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SliceOffsetInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SliceOffsetInfo proto.InternalMessageInfo

func (m *SliceOffsetInfo) GetSliceHash() string {
	if m != nil {
		return m.SliceHash
	}
	return ""
}

func (m *SliceOffsetInfo) GetSliceOffset() *SliceOffset {
	if m != nil {
		return m.SliceOffset
	}
	return nil
}

type SliceOffset struct {
	SliceOffsetStart     uint64   `protobuf:"varint,1,opt,name=slice_offset_start,json=sliceOffsetStart,proto3" json:"slice_offset_start,omitempty"`
	SliceOffsetEnd       uint64   `protobuf:"varint,2,opt,name=slice_offset_end,json=sliceOffsetEnd,proto3" json:"slice_offset_end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SliceOffset) Reset()         { *m = SliceOffset{} }
func (m *SliceOffset) String() string { return proto.CompactTextString(m) }
func (*SliceOffset) ProtoMessage()    {}
func (*SliceOffset) Descriptor() ([]byte, []int) {
	return fileDescriptor_12078ceca3ea879d, []int{5}
}

func (m *SliceOffset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SliceOffset.Unmarshal(m, b)
}
func (m *SliceOffset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SliceOffset.Marshal(b, m, deterministic)
}
func (m *SliceOffset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SliceOffset.Merge(m, src)
}
func (m *SliceOffset) XXX_Size() int {
	return xxx_messageInfo_SliceOffset.Size(m)
}
func (m *SliceOffset) XXX_DiscardUnknown() {
	xxx_messageInfo_SliceOffset.DiscardUnknown(m)
}

var xxx_messageInfo_SliceOffset proto.InternalMessageInfo

func (m *SliceOffset) GetSliceOffsetStart() uint64 {
	if m != nil {
		return m.SliceOffsetStart
	}
	return 0
}

func (m *SliceOffset) GetSliceOffsetEnd() uint64 {
	if m != nil {
		return m.SliceOffsetEnd
	}
	return 0
}

type FileIndexes struct {
	//  string file_hash = 1; // file hash
	FilePath             string   `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	P2PAddress           string   `protobuf:"bytes,2,opt,name=p2p_address,json=p2pAddress,proto3" json:"p2p_address,omitempty"`
	WalletAddress        string   `protobuf:"bytes,3,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	SavePath             string   `protobuf:"bytes,4,opt,name=save_path,json=savePath,proto3" json:"save_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileIndexes) Reset()         { *m = FileIndexes{} }
func (m *FileIndexes) String() string { return proto.CompactTextString(m) }
func (*FileIndexes) ProtoMessage()    {}
func (*FileIndexes) Descriptor() ([]byte, []int) {
	return fileDescriptor_12078ceca3ea879d, []int{6}
}

func (m *FileIndexes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileIndexes.Unmarshal(m, b)
}
func (m *FileIndexes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileIndexes.Marshal(b, m, deterministic)
}
func (m *FileIndexes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileIndexes.Merge(m, src)
}
func (m *FileIndexes) XXX_Size() int {
	return xxx_messageInfo_FileIndexes.Size(m)
}
func (m *FileIndexes) XXX_DiscardUnknown() {
	xxx_messageInfo_FileIndexes.DiscardUnknown(m)
}

var xxx_messageInfo_FileIndexes proto.InternalMessageInfo

func (m *FileIndexes) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *FileIndexes) GetP2PAddress() string {
	if m != nil {
		return m.P2PAddress
	}
	return ""
}

func (m *FileIndexes) GetWalletAddress() string {
	if m != nil {
		return m.WalletAddress
	}
	return ""
}

func (m *FileIndexes) GetSavePath() string {
	if m != nil {
		return m.SavePath
	}
	return ""
}

type DownloadSliceInfo struct {
	SliceStorageInfo     *SliceStorageInfo `protobuf:"bytes,1,opt,name=slice_storage_info,json=sliceStorageInfo,proto3" json:"slice_storage_info,omitempty"`
	SliceNumber          uint64            `protobuf:"varint,2,opt,name=slice_number,json=sliceNumber,proto3" json:"slice_number,omitempty"`
	StoragePpInfo        *PPBaseInfo       `protobuf:"bytes,3,opt,name=storage_pp_info,json=storagePpInfo,proto3" json:"storage_pp_info,omitempty"`
	BackupsPpInfo        *PPBaseInfo       `protobuf:"bytes,4,opt,name=backups_pp_info,json=backupsPpInfo,proto3" json:"backups_pp_info,omitempty"`
	VisitResult          bool              `protobuf:"varint,5,opt,name=visit_result,json=visitResult,proto3" json:"visit_result,omitempty"`
	TaskId               string            `protobuf:"bytes,6,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SliceOffset          *SliceOffset      `protobuf:"bytes,7,opt,name=slice_offset,json=sliceOffset,proto3" json:"slice_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DownloadSliceInfo) Reset()         { *m = DownloadSliceInfo{} }
func (m *DownloadSliceInfo) String() string { return proto.CompactTextString(m) }
func (*DownloadSliceInfo) ProtoMessage()    {}
func (*DownloadSliceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_12078ceca3ea879d, []int{7}
}

func (m *DownloadSliceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadSliceInfo.Unmarshal(m, b)
}
func (m *DownloadSliceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadSliceInfo.Marshal(b, m, deterministic)
}
func (m *DownloadSliceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadSliceInfo.Merge(m, src)
}
func (m *DownloadSliceInfo) XXX_Size() int {
	return xxx_messageInfo_DownloadSliceInfo.Size(m)
}
func (m *DownloadSliceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadSliceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadSliceInfo proto.InternalMessageInfo

func (m *DownloadSliceInfo) GetSliceStorageInfo() *SliceStorageInfo {
	if m != nil {
		return m.SliceStorageInfo
	}
	return nil
}

func (m *DownloadSliceInfo) GetSliceNumber() uint64 {
	if m != nil {
		return m.SliceNumber
	}
	return 0
}

func (m *DownloadSliceInfo) GetStoragePpInfo() *PPBaseInfo {
	if m != nil {
		return m.StoragePpInfo
	}
	return nil
}

func (m *DownloadSliceInfo) GetBackupsPpInfo() *PPBaseInfo {
	if m != nil {
		return m.BackupsPpInfo
	}
	return nil
}

func (m *DownloadSliceInfo) GetVisitResult() bool {
	if m != nil {
		return m.VisitResult
	}
	return false
}

func (m *DownloadSliceInfo) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *DownloadSliceInfo) GetSliceOffset() *SliceOffset {
	if m != nil {
		return m.SliceOffset
	}
	return nil
}

type SliceStorageInfo struct {
	SliceSize            uint64   `protobuf:"varint,1,opt,name=slice_size,json=sliceSize,proto3" json:"slice_size,omitempty"`
	SliceHash            string   `protobuf:"bytes,2,opt,name=slice_hash,json=sliceHash,proto3" json:"slice_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SliceStorageInfo) Reset()         { *m = SliceStorageInfo{} }
func (m *SliceStorageInfo) String() string { return proto.CompactTextString(m) }
func (*SliceStorageInfo) ProtoMessage()    {}
func (*SliceStorageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_12078ceca3ea879d, []int{8}
}

func (m *SliceStorageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SliceStorageInfo.Unmarshal(m, b)
}
func (m *SliceStorageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SliceStorageInfo.Marshal(b, m, deterministic)
}
func (m *SliceStorageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SliceStorageInfo.Merge(m, src)
}
func (m *SliceStorageInfo) XXX_Size() int {
	return xxx_messageInfo_SliceStorageInfo.Size(m)
}
func (m *SliceStorageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SliceStorageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SliceStorageInfo proto.InternalMessageInfo

func (m *SliceStorageInfo) GetSliceSize() uint64 {
	if m != nil {
		return m.SliceSize
	}
	return 0
}

func (m *SliceStorageInfo) GetSliceHash() string {
	if m != nil {
		return m.SliceHash
	}
	return ""
}

type ShareLinkInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FileHash             string   `protobuf:"bytes,2,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	LinkTime             uint64   `protobuf:"varint,3,opt,name=link_time,json=linkTime,proto3" json:"link_time,omitempty"`
	FileSize             uint64   `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	LinkTimeExp          uint64   `protobuf:"varint,5,opt,name=link_time_exp,json=linkTimeExp,proto3" json:"link_time_exp,omitempty"`
	ShareId              string   `protobuf:"bytes,6,opt,name=share_id,json=shareId,proto3" json:"share_id,omitempty"`
	IsDirectory          bool     `protobuf:"varint,7,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	ShareLink            string   `protobuf:"bytes,8,opt,name=share_link,json=shareLink,proto3" json:"share_link,omitempty"`
	IsPrivate            bool     `protobuf:"varint,9,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	ShareLinkPassword    string   `protobuf:"bytes,10,opt,name=share_link_password,json=shareLinkPassword,proto3" json:"share_link_password,omitempty"`
	OwnerWalletAddress   string   `protobuf:"bytes,11,opt,name=owner_wallet_address,json=ownerWalletAddress,proto3" json:"owner_wallet_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShareLinkInfo) Reset()         { *m = ShareLinkInfo{} }
func (m *ShareLinkInfo) String() string { return proto.CompactTextString(m) }
func (*ShareLinkInfo) ProtoMessage()    {}
func (*ShareLinkInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_12078ceca3ea879d, []int{9}
}

func (m *ShareLinkInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShareLinkInfo.Unmarshal(m, b)
}
func (m *ShareLinkInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShareLinkInfo.Marshal(b, m, deterministic)
}
func (m *ShareLinkInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareLinkInfo.Merge(m, src)
}
func (m *ShareLinkInfo) XXX_Size() int {
	return xxx_messageInfo_ShareLinkInfo.Size(m)
}
func (m *ShareLinkInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareLinkInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ShareLinkInfo proto.InternalMessageInfo

func (m *ShareLinkInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ShareLinkInfo) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *ShareLinkInfo) GetLinkTime() uint64 {
	if m != nil {
		return m.LinkTime
	}
	return 0
}

func (m *ShareLinkInfo) GetFileSize() uint64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *ShareLinkInfo) GetLinkTimeExp() uint64 {
	if m != nil {
		return m.LinkTimeExp
	}
	return 0
}

func (m *ShareLinkInfo) GetShareId() string {
	if m != nil {
		return m.ShareId
	}
	return ""
}

func (m *ShareLinkInfo) GetIsDirectory() bool {
	if m != nil {
		return m.IsDirectory
	}
	return false
}

func (m *ShareLinkInfo) GetShareLink() string {
	if m != nil {
		return m.ShareLink
	}
	return ""
}

func (m *ShareLinkInfo) GetIsPrivate() bool {
	if m != nil {
		return m.IsPrivate
	}
	return false
}

func (m *ShareLinkInfo) GetShareLinkPassword() string {
	if m != nil {
		return m.ShareLinkPassword
	}
	return ""
}

func (m *ShareLinkInfo) GetOwnerWalletAddress() string {
	if m != nil {
		return m.OwnerWalletAddress
	}
	return ""
}

type AlbumInfo struct {
	AlbumId              string    `protobuf:"bytes,1,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	AlbumName            string    `protobuf:"bytes,2,opt,name=album_name,json=albumName,proto3" json:"album_name,omitempty"`
	AlbumBlurb           string    `protobuf:"bytes,3,opt,name=album_blurb,json=albumBlurb,proto3" json:"album_blurb,omitempty"`
	AlbumVisit           int64     `protobuf:"varint,4,opt,name=album_visit,json=albumVisit,proto3" json:"album_visit,omitempty"`
	AlbumTime            int64     `protobuf:"varint,5,opt,name=album_time,json=albumTime,proto3" json:"album_time,omitempty"`
	AlbumCoverLink       string    `protobuf:"bytes,6,opt,name=album_cover_link,json=albumCoverLink,proto3" json:"album_cover_link,omitempty"`
	IsPrivate            bool      `protobuf:"varint,7,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	AlbumType            AlbumType `protobuf:"varint,8,opt,name=album_type,json=albumType,proto3,enum=protos.AlbumType" json:"album_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AlbumInfo) Reset()         { *m = AlbumInfo{} }
func (m *AlbumInfo) String() string { return proto.CompactTextString(m) }
func (*AlbumInfo) ProtoMessage()    {}
func (*AlbumInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_12078ceca3ea879d, []int{10}
}

func (m *AlbumInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlbumInfo.Unmarshal(m, b)
}
func (m *AlbumInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlbumInfo.Marshal(b, m, deterministic)
}
func (m *AlbumInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlbumInfo.Merge(m, src)
}
func (m *AlbumInfo) XXX_Size() int {
	return xxx_messageInfo_AlbumInfo.Size(m)
}
func (m *AlbumInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AlbumInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AlbumInfo proto.InternalMessageInfo

func (m *AlbumInfo) GetAlbumId() string {
	if m != nil {
		return m.AlbumId
	}
	return ""
}

func (m *AlbumInfo) GetAlbumName() string {
	if m != nil {
		return m.AlbumName
	}
	return ""
}

func (m *AlbumInfo) GetAlbumBlurb() string {
	if m != nil {
		return m.AlbumBlurb
	}
	return ""
}

func (m *AlbumInfo) GetAlbumVisit() int64 {
	if m != nil {
		return m.AlbumVisit
	}
	return 0
}

func (m *AlbumInfo) GetAlbumTime() int64 {
	if m != nil {
		return m.AlbumTime
	}
	return 0
}

func (m *AlbumInfo) GetAlbumCoverLink() string {
	if m != nil {
		return m.AlbumCoverLink
	}
	return ""
}

func (m *AlbumInfo) GetIsPrivate() bool {
	if m != nil {
		return m.IsPrivate
	}
	return false
}

func (m *AlbumInfo) GetAlbumType() AlbumType {
	if m != nil {
		return m.AlbumType
	}
	return AlbumType_ALL
}

type AlbumNumber struct {
	All                  int64    `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	Video                int64    `protobuf:"varint,2,opt,name=video,proto3" json:"video,omitempty"`
	Music                int64    `protobuf:"varint,3,opt,name=music,proto3" json:"music,omitempty"`
	Other                int64    `protobuf:"varint,4,opt,name=other,proto3" json:"other,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlbumNumber) Reset()         { *m = AlbumNumber{} }
func (m *AlbumNumber) String() string { return proto.CompactTextString(m) }
func (*AlbumNumber) ProtoMessage()    {}
func (*AlbumNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_12078ceca3ea879d, []int{11}
}

func (m *AlbumNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlbumNumber.Unmarshal(m, b)
}
func (m *AlbumNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlbumNumber.Marshal(b, m, deterministic)
}
func (m *AlbumNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlbumNumber.Merge(m, src)
}
func (m *AlbumNumber) XXX_Size() int {
	return xxx_messageInfo_AlbumNumber.Size(m)
}
func (m *AlbumNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_AlbumNumber.DiscardUnknown(m)
}

var xxx_messageInfo_AlbumNumber proto.InternalMessageInfo

func (m *AlbumNumber) GetAll() int64 {
	if m != nil {
		return m.All
	}
	return 0
}

func (m *AlbumNumber) GetVideo() int64 {
	if m != nil {
		return m.Video
	}
	return 0
}

func (m *AlbumNumber) GetMusic() int64 {
	if m != nil {
		return m.Music
	}
	return 0
}

func (m *AlbumNumber) GetOther() int64 {
	if m != nil {
		return m.Other
	}
	return 0
}

func init() {
	proto.RegisterEnum("protos.ResultState", ResultState_name, ResultState_value)
	proto.RegisterEnum("protos.DownloadWrongType", DownloadWrongType_name, DownloadWrongType_value)
	proto.RegisterEnum("protos.AlbumType", AlbumType_name, AlbumType_value)
	proto.RegisterEnum("protos.AlbumSortType", AlbumSortType_name, AlbumSortType_value)
	proto.RegisterEnum("protos.FileSortType", FileSortType_name, FileSortType_value)
	proto.RegisterEnum("protos.MsgType", MsgType_name, MsgType_value)
	proto.RegisterType((*Result)(nil), "protos.Result")
	proto.RegisterType((*PPBaseInfo)(nil), "protos.PPBaseInfo")
	proto.RegisterType((*FileInfo)(nil), "protos.FileInfo")
	proto.RegisterType((*SliceNumAddr)(nil), "protos.SliceNumAddr")
	proto.RegisterType((*SliceOffsetInfo)(nil), "protos.SliceOffsetInfo")
	proto.RegisterType((*SliceOffset)(nil), "protos.SliceOffset")
	proto.RegisterType((*FileIndexes)(nil), "protos.FileIndexes")
	proto.RegisterType((*DownloadSliceInfo)(nil), "protos.DownloadSliceInfo")
	proto.RegisterType((*SliceStorageInfo)(nil), "protos.SliceStorageInfo")
	proto.RegisterType((*ShareLinkInfo)(nil), "protos.ShareLinkInfo")
	proto.RegisterType((*AlbumInfo)(nil), "protos.AlbumInfo")
	proto.RegisterType((*AlbumNumber)(nil), "protos.AlbumNumber")
}

func init() { proto.RegisterFile("sds_comm.proto", fileDescriptor_12078ceca3ea879d) }

var fileDescriptor_12078ceca3ea879d = []byte{
	// 1147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x36, 0x45, 0x59, 0x14, 0x87, 0x96, 0xcc, 0x6c, 0x82, 0x46, 0x69, 0x10, 0x34, 0x21, 0x50,
	0xc4, 0x75, 0x03, 0x23, 0x70, 0xd1, 0x1e, 0x7a, 0x53, 0x6c, 0x1a, 0x21, 0x20, 0xdb, 0x02, 0x29,
	0x3b, 0x40, 0x2f, 0xc4, 0x4a, 0x5c, 0x5b, 0x84, 0x29, 0x92, 0xd8, 0xa5, 0xfc, 0x13, 0xa0, 0xcf,
	0xd0, 0x5b, 0xef, 0x7d, 0xbd, 0x02, 0x7d, 0x83, 0x1e, 0x8a, 0x9d, 0x25, 0xa9, 0x1f, 0xdb, 0x48,
	0xd0, 0x93, 0x76, 0xbf, 0x99, 0xd9, 0xd9, 0xfd, 0x66, 0xe6, 0xa3, 0xa0, 0x2b, 0x22, 0x11, 0x4e,
	0xb2, 0xd9, 0x6c, 0x2f, 0xe7, 0x59, 0x91, 0x91, 0x16, 0xfe, 0x08, 0xc7, 0x85, 0x96, 0xcf, 0xc4,
	0x3c, 0x29, 0xc8, 0x0f, 0xb0, 0x29, 0x0a, 0x5a, 0xb0, 0x9e, 0xf6, 0x5a, 0xdb, 0xe9, 0xee, 0x3f,
	0x55, 0x8e, 0x62, 0x4f, 0x99, 0x03, 0x69, 0xf2, 0x95, 0x07, 0xb1, 0x41, 0x9f, 0x89, 0xcb, 0x5e,
	0xe3, 0xb5, 0xb6, 0x63, 0xfa, 0x72, 0xe9, 0xfc, 0x0e, 0x30, 0x1c, 0x7e, 0xa0, 0x82, 0x79, 0xe9,
	0x45, 0x46, 0xbe, 0x03, 0x2b, 0xdf, 0xcf, 0x43, 0x1a, 0x45, 0x9c, 0x09, 0x81, 0x07, 0x9a, 0x3e,
	0xe4, 0xfb, 0x79, 0x5f, 0x21, 0xe4, 0x7b, 0xe8, 0xde, 0xd0, 0x24, 0x61, 0x45, 0xed, 0xa3, 0xce,
	0xea, 0x28, 0xb4, 0x72, 0x7b, 0x0b, 0xdb, 0x29, 0x2b, 0x6e, 0x32, 0x7e, 0x55, 0xfb, 0xe9, 0xe8,
	0xd7, 0x2d, 0xe1, 0xd2, 0xd1, 0xf9, 0xa7, 0x01, 0xed, 0xa3, 0x38, 0x51, 0xd9, 0x5f, 0x82, 0x79,
	0x11, 0x27, 0x2c, 0x14, 0xf1, 0x67, 0xf5, 0x98, 0xa6, 0xdf, 0x96, 0x40, 0x10, 0x7f, 0x66, 0xb5,
	0x71, 0x4a, 0xc5, 0xb4, 0x4c, 0x8a, 0xc6, 0x8f, 0x54, 0x4c, 0x6b, 0x63, 0x4a, 0x67, 0xac, 0xcc,
	0x84, 0xc6, 0x13, 0x3a, 0x63, 0xf2, 0x51, 0x13, 0xce, 0x68, 0xc1, 0xc2, 0x22, 0x9e, 0xb1, 0x5e,
	0x13, 0x0f, 0x06, 0x05, 0x8d, 0xe2, 0x19, 0x23, 0x6f, 0x60, 0x2b, 0x16, 0x61, 0x14, 0x73, 0x36,
	0x29, 0x32, 0x7e, 0xd7, 0xdb, 0x7c, 0xad, 0xed, 0xb4, 0x7d, 0x2b, 0x16, 0x87, 0x15, 0x24, 0x5d,
	0x44, 0x91, 0x71, 0x7a, 0xc9, 0xc2, 0x9c, 0x16, 0xd3, 0x5e, 0x0b, 0x73, 0x58, 0x25, 0x36, 0xa4,
	0xc5, 0x94, 0xbc, 0x02, 0x88, 0x45, 0x98, 0xf3, 0xf8, 0x5a, 0xd6, 0xc2, 0xc0, 0x33, 0xcc, 0x58,
	0x0c, 0x15, 0x40, 0xde, 0xc3, 0xb3, 0xec, 0x26, 0x65, 0x3c, 0x5c, 0xe3, 0xaf, 0x8d, 0x27, 0x11,
	0xb4, 0x7d, 0x5a, 0x21, 0xf1, 0x15, 0x80, 0x98, 0x52, 0xce, 0xc2, 0x24, 0x4e, 0xaf, 0x7a, 0x26,
	0xfa, 0x99, 0x88, 0x0c, 0xe2, 0xf4, 0x8a, 0x3c, 0x07, 0x43, 0x64, 0xbc, 0x08, 0xe3, 0xa8, 0x07,
	0xf8, 0xa4, 0x96, 0xdc, 0x7a, 0x11, 0xf9, 0x16, 0xda, 0xd1, 0x9c, 0xd3, 0x22, 0xce, 0xd2, 0x9e,
	0xa5, 0x58, 0xac, 0xf6, 0xce, 0x9f, 0x1a, 0x6c, 0x05, 0x49, 0x3c, 0x61, 0x27, 0xf3, 0x99, 0xcc,
	0x83, 0x0f, 0x93, 0xfb, 0x30, 0x9d, 0xcf, 0xc6, 0x8c, 0x97, 0xb4, 0x5b, 0xa2, 0xf4, 0x19, 0x33,
	0x4e, 0x7e, 0xa9, 0x5c, 0xb2, 0x8b, 0x0b, 0xc1, 0x0a, 0x24, 0xdf, 0x5a, 0xb4, 0x19, 0x1e, 0x77,
	0x8a, 0xa6, 0x32, 0x4e, 0x6d, 0xc8, 0x8f, 0x60, 0xe4, 0x79, 0x18, 0xa7, 0x17, 0x19, 0x96, 0xc4,
	0xda, 0x27, 0x55, 0xc8, 0xa2, 0xe3, 0xfc, 0x56, 0x9e, 0xcb, 0x5f, 0x67, 0x0a, 0xdb, 0x4b, 0x07,
	0x61, 0x3b, 0xc8, 0xf7, 0x63, 0x5e, 0x2c, 0xb9, 0x56, 0xbe, 0x5f, 0x22, 0x58, 0xf3, 0xff, 0x79,
	0x2d, 0x87, 0x81, 0xb5, 0x64, 0x23, 0xef, 0x80, 0x2c, 0x1f, 0x13, 0x8a, 0x82, 0xf2, 0xa2, 0xa4,
	0xc1, 0x5e, 0x8a, 0x0b, 0x24, 0x4e, 0x76, 0xc0, 0x5e, 0xf1, 0x66, 0x69, 0x84, 0x89, 0x9b, 0x7e,
	0x77, 0xc9, 0xd7, 0x4d, 0x23, 0xe7, 0x0f, 0x0d, 0x2c, 0xd5, 0xd9, 0x11, 0xbb, 0x65, 0xa2, 0x6e,
	0x51, 0x6c, 0x1f, 0x6d, 0xd1, 0xa2, 0xd8, 0x3b, 0x6b, 0x73, 0xd7, 0xf8, 0x8a, 0xb9, 0xd3, 0x1f,
	0x9a, 0xbb, 0x97, 0x60, 0x0a, 0x7a, 0x5d, 0x26, 0x69, 0xaa, 0x24, 0x12, 0x90, 0x49, 0x9c, 0xbf,
	0x1b, 0xf0, 0xe4, 0x30, 0xbb, 0x49, 0x93, 0x8c, 0x46, 0xc8, 0x00, 0xb2, 0x7c, 0x54, 0xbd, 0xbf,
	0xea, 0x6f, 0x2c, 0x98, 0x86, 0x64, 0xf6, 0x56, 0xc8, 0x0c, 0x94, 0x03, 0x96, 0x4d, 0xb1, 0xb0,
	0x84, 0xdc, 0x6b, 0xa4, 0xc6, 0xfd, 0x46, 0xfa, 0x15, 0xb6, 0xeb, 0x21, 0xfa, 0x62, 0x63, 0x74,
	0xaa, 0xd9, 0xc2, 0xfe, 0x90, 0xb1, 0x63, 0x3a, 0xb9, 0x9a, 0xe7, 0xa2, 0x8e, 0x6d, 0x3e, 0x1e,
	0x5b, 0xba, 0x96, 0xb1, 0x6f, 0x60, 0xeb, 0x3a, 0x16, 0x71, 0x11, 0x72, 0x54, 0xc4, 0x6a, 0xbe,
	0x11, 0x2b, 0x35, 0xf4, 0x39, 0x18, 0x05, 0x15, 0x57, 0x72, 0x98, 0xd4, 0x68, 0xb7, 0xe4, 0xd6,
	0x8b, 0xee, 0x75, 0x99, 0xf1, 0x95, 0x5d, 0x36, 0x04, 0x7b, 0x9d, 0xb4, 0x45, 0x43, 0x2f, 0x09,
	0x9c, 0x6a, 0x68, 0x54, 0xb8, 0xd5, 0x7e, 0x6f, 0xac, 0xf5, 0xbb, 0xf3, 0x6f, 0x03, 0x3a, 0x41,
	0x35, 0xfd, 0x78, 0x1e, 0x81, 0x26, 0x0a, 0x9e, 0xea, 0x26, 0x5c, 0x7f, 0x51, 0x26, 0xa5, 0x96,
	0x28, 0x1d, 0xd4, 0x95, 0x34, 0x48, 0x00, 0x55, 0x70, 0x45, 0x7d, 0x9b, 0x6b, 0xea, 0xeb, 0x40,
	0xa7, 0x8e, 0x0c, 0xd9, 0x6d, 0x8e, 0x1c, 0x36, 0x7d, 0xab, 0x8a, 0x76, 0x6f, 0x73, 0xf2, 0x02,
	0xda, 0x4a, 0xaf, 0x6a, 0x12, 0x0d, 0xdc, 0x7b, 0xd1, 0x3d, 0x85, 0x35, 0xee, 0x2b, 0xec, 0xaa,
	0xda, 0xb5, 0xd7, 0xd5, 0x6e, 0x55, 0x5d, 0xcd, 0x75, 0x75, 0xdd, 0x83, 0xa7, 0x8b, 0xe8, 0x30,
	0xa7, 0x42, 0xdc, 0x64, 0x5c, 0x09, 0xa3, 0xe9, 0x3f, 0xa9, 0x8f, 0x19, 0x96, 0x86, 0x47, 0xd5,
	0xd8, 0x7a, 0x4c, 0x8d, 0x9d, 0xbf, 0x1a, 0x60, 0xf6, 0x93, 0xf1, 0x7c, 0x86, 0xd4, 0xbf, 0x80,
	0x36, 0x95, 0x1b, 0xf9, 0x56, 0x45, 0xbf, 0x81, 0x7b, 0x2f, 0x92, 0x37, 0x55, 0x26, 0xac, 0x4d,
	0x59, 0x46, 0x44, 0xaa, 0xaf, 0x91, 0x32, 0x8f, 0x93, 0x39, 0x1f, 0x97, 0x63, 0xac, 0x22, 0x3e,
	0x48, 0x64, 0xe1, 0x80, 0xfd, 0x89, 0x95, 0xd0, 0x4b, 0x87, 0x73, 0x89, 0x2c, 0x12, 0x60, 0x19,
	0x37, 0xd1, 0xae, 0x12, 0x60, 0x1d, 0x77, 0xc0, 0x56, 0xe6, 0x49, 0x76, 0xcd, 0xb8, 0xa2, 0x53,
	0x95, 0xa3, 0x8b, 0xf8, 0x81, 0x84, 0x1f, 0xe0, 0xf4, 0x81, 0x2f, 0x56, 0x95, 0xe7, 0x2e, 0x67,
	0x58, 0x91, 0xee, 0xfe, 0x93, 0xaa, 0xf1, 0x91, 0x8a, 0xd1, 0x5d, 0xce, 0xaa, 0xd4, 0x77, 0x39,
	0x73, 0x28, 0x58, 0x88, 0x97, 0xf3, 0x6e, 0x83, 0x4e, 0x93, 0x04, 0xf9, 0xd1, 0x7d, 0xb9, 0x24,
	0xcf, 0x60, 0xf3, 0x3a, 0x8e, 0x58, 0x86, 0xb4, 0xe8, 0xbe, 0xda, 0x48, 0x74, 0x36, 0x17, 0xf1,
	0x04, 0xc9, 0xd0, 0x7d, 0xb5, 0x91, 0x68, 0x56, 0x4c, 0x19, 0x2f, 0x19, 0x50, 0x9b, 0xdd, 0x77,
	0x60, 0x2d, 0xfd, 0xaf, 0x21, 0xdb, 0x60, 0xf9, 0x6e, 0x10, 0x06, 0x67, 0x07, 0x07, 0x6e, 0x10,
	0xd8, 0x1b, 0x64, 0x0b, 0xda, 0x12, 0x38, 0xea, 0x7b, 0x03, 0x5b, 0xdb, 0x7d, 0xbf, 0x50, 0xbc,
	0x4f, 0x3c, 0x4b, 0x2f, 0xe5, 0x2d, 0x49, 0x07, 0xcc, 0xc1, 0x69, 0xe0, 0x06, 0x03, 0xef, 0xc0,
	0x55, 0x11, 0xa7, 0xe7, 0xae, 0x3f, 0xf2, 0x8e, 0x5d, 0x5b, 0xdb, 0xfd, 0xb9, 0xac, 0x32, 0x7a,
	0x1a, 0xa0, 0xf7, 0x07, 0x03, 0x7b, 0x83, 0x98, 0xb0, 0x79, 0xee, 0x1d, 0xba, 0xa7, 0xb6, 0x26,
	0x97, 0xc7, 0x67, 0x81, 0x77, 0x60, 0x37, 0xe4, 0xf2, 0x74, 0xf4, 0xd1, 0xf5, 0x6d, 0x7d, 0xf7,
	0x2d, 0x74, 0x30, 0x2c, 0xc8, 0x78, 0x81, 0xa1, 0x00, 0xad, 0x41, 0x7f, 0xe4, 0x06, 0x23, 0x7b,
	0x43, 0xae, 0xcf, 0xbd, 0xc0, 0x1b, 0x05, 0x78, 0xfe, 0x96, 0xfc, 0x2a, 0xd4, 0x7e, 0x06, 0xe8,
	0x87, 0xee, 0x91, 0xbd, 0x41, 0xda, 0xd0, 0x54, 0x57, 0x90, 0xab, 0xc0, 0xfb, 0xcd, 0xb5, 0x1b,
	0x72, 0x75, 0xd2, 0x3f, 0x76, 0x6d, 0x7d, 0xf7, 0x1b, 0x30, 0x8e, 0x85, 0xba, 0xbe, 0x05, 0xc6,
	0xa1, 0x7b, 0xd4, 0x3f, 0x1b, 0x8c, 0xec, 0x8d, 0xb1, 0xfa, 0x37, 0xf8, 0xd3, 0x7f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xfd, 0x75, 0x1a, 0x93, 0x26, 0x0a, 0x00, 0x00,
}
