Port: :18082
NetworkAddress: 127.0.0.1
SPNetworkId: sdm://stpub1qjexvmuzq5tn95g7cr7sd945suvsuxqcq4h5z6w08wywnhlt7ujn4pkjmmkfk055p03d5smtf93wq2utcf50fq6ahyan32usfa6zjlaqdstk56@127.0.0.1:8888
Debug: true
PPListDir: "./peers/pp-list"
AccountDir: "./account"
scryptN: 4096
scryptP: 6
DefPassword:
DefSavePath:
StorehousePath:
DownloadPath:
Password: aaa
Account: st1rgfaumqggksfw9vr2asuq9flyywam8lrvzmq9s
AutoRun: true
Internal: true
IsWallet:
BPURL:
IsCheckDefaultPath:
IsLimitDownloadSpeed: true
LimitDownloadSpeed: 100
IsLimitUploadSpeed: true
LimitUploadSpeed: 100
IsCheckFileOperation:
IsCheckFileTransferFinished:
AddressPrefix: "st"
ChainId: "test-chain"
Token: "stos"
StratosChainAddress: 127.0.0.1
StratosChainPort: 1317